
/*
Auto-generated by CVXPYgen on June 22, 2026 at 18:17:08
Content: Function declarations
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include "cpg_workspace.h"

// Update user-defined parameter values
extern void cpg_update_x_ref(cpg_int idx, cpg_float val);
extern void cpg_update_x0(cpg_int idx, cpg_float val);
extern void cpg_update_B_0(cpg_int idx, cpg_float val);
extern void cpg_update_B_1(cpg_int idx, cpg_float val);
extern void cpg_update_B_2(cpg_int idx, cpg_float val);
extern void cpg_update_B_3(cpg_int idx, cpg_float val);
extern void cpg_update_B_4(cpg_int idx, cpg_float val);
extern void cpg_update_B_5(cpg_int idx, cpg_float val);
extern void cpg_update_B_6(cpg_int idx, cpg_float val);
extern void cpg_update_B_7(cpg_int idx, cpg_float val);
extern void cpg_update_B_8(cpg_int idx, cpg_float val);
extern void cpg_update_B_9(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_0(cpg_float val);
extern void cpg_update_n_0_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_1(cpg_float val);
extern void cpg_update_n_0_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_2(cpg_float val);
extern void cpg_update_n_0_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_3(cpg_float val);
extern void cpg_update_n_0_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_4(cpg_float val);
extern void cpg_update_n_0_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_0_5(cpg_float val);
extern void cpg_update_n_0_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_0(cpg_float val);
extern void cpg_update_n_1_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_1(cpg_float val);
extern void cpg_update_n_1_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_2(cpg_float val);
extern void cpg_update_n_1_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_3(cpg_float val);
extern void cpg_update_n_1_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_4(cpg_float val);
extern void cpg_update_n_1_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_1_5(cpg_float val);
extern void cpg_update_n_1_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_0(cpg_float val);
extern void cpg_update_n_2_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_1(cpg_float val);
extern void cpg_update_n_2_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_2(cpg_float val);
extern void cpg_update_n_2_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_3(cpg_float val);
extern void cpg_update_n_2_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_4(cpg_float val);
extern void cpg_update_n_2_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_2_5(cpg_float val);
extern void cpg_update_n_2_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_0(cpg_float val);
extern void cpg_update_n_3_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_1(cpg_float val);
extern void cpg_update_n_3_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_2(cpg_float val);
extern void cpg_update_n_3_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_3(cpg_float val);
extern void cpg_update_n_3_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_4(cpg_float val);
extern void cpg_update_n_3_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_3_5(cpg_float val);
extern void cpg_update_n_3_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_0(cpg_float val);
extern void cpg_update_n_4_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_1(cpg_float val);
extern void cpg_update_n_4_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_2(cpg_float val);
extern void cpg_update_n_4_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_3(cpg_float val);
extern void cpg_update_n_4_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_4(cpg_float val);
extern void cpg_update_n_4_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_4_5(cpg_float val);
extern void cpg_update_n_4_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_0(cpg_float val);
extern void cpg_update_n_5_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_1(cpg_float val);
extern void cpg_update_n_5_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_2(cpg_float val);
extern void cpg_update_n_5_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_3(cpg_float val);
extern void cpg_update_n_5_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_4(cpg_float val);
extern void cpg_update_n_5_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_5_5(cpg_float val);
extern void cpg_update_n_5_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_0(cpg_float val);
extern void cpg_update_n_6_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_1(cpg_float val);
extern void cpg_update_n_6_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_2(cpg_float val);
extern void cpg_update_n_6_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_3(cpg_float val);
extern void cpg_update_n_6_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_4(cpg_float val);
extern void cpg_update_n_6_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_6_5(cpg_float val);
extern void cpg_update_n_6_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_0(cpg_float val);
extern void cpg_update_n_7_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_1(cpg_float val);
extern void cpg_update_n_7_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_2(cpg_float val);
extern void cpg_update_n_7_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_3(cpg_float val);
extern void cpg_update_n_7_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_4(cpg_float val);
extern void cpg_update_n_7_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_7_5(cpg_float val);
extern void cpg_update_n_7_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_0(cpg_float val);
extern void cpg_update_n_8_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_1(cpg_float val);
extern void cpg_update_n_8_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_2(cpg_float val);
extern void cpg_update_n_8_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_3(cpg_float val);
extern void cpg_update_n_8_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_4(cpg_float val);
extern void cpg_update_n_8_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_8_5(cpg_float val);
extern void cpg_update_n_8_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_0(cpg_float val);
extern void cpg_update_n_9_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_1(cpg_float val);
extern void cpg_update_n_9_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_2(cpg_float val);
extern void cpg_update_n_9_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_3(cpg_float val);
extern void cpg_update_n_9_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_4(cpg_float val);
extern void cpg_update_n_9_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_9_5(cpg_float val);
extern void cpg_update_n_9_5(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_0(cpg_float val);
extern void cpg_update_n_10_0(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_1(cpg_float val);
extern void cpg_update_n_10_1(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_2(cpg_float val);
extern void cpg_update_n_10_2(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_3(cpg_float val);
extern void cpg_update_n_10_3(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_4(cpg_float val);
extern void cpg_update_n_10_4(cpg_int idx, cpg_float val);
extern void cpg_update_d_10_5(cpg_float val);
extern void cpg_update_n_10_5(cpg_int idx, cpg_float val);

// Map user-defined to canonical parameters
extern void cpg_canonicalize_q();
extern void cpg_canonicalize_A();
extern void cpg_canonicalize_l();
extern void cpg_canonicalize_u();

// Retrieve dual solution in terms of user-defined constraints
extern void cpg_retrieve_dual();

// Retrieve solver information
extern void cpg_retrieve_info();

// Solve via canonicalization, canonical solve, retrieval
extern void cpg_solve();

// Update solver settings
extern void cpg_set_solver_default_settings();
extern void cpg_set_solver_max_iter(cpg_int max_iter_new);
extern void cpg_set_solver_eps_abs(cpg_float eps_abs_new);
extern void cpg_set_solver_eps_rel(cpg_float eps_rel_new);
extern void cpg_set_solver_eps_prim_inf(cpg_float eps_prim_inf_new);
extern void cpg_set_solver_eps_dual_inf(cpg_float eps_dual_inf_new);
extern void cpg_set_solver_scaled_termination(cpg_int scaled_termination_new);
extern void cpg_set_solver_check_termination(cpg_int check_termination_new);
extern void cpg_set_solver_warm_starting(cpg_int warm_starting_new);
