#!/usr/bin/env python3
"""Iterative-MPC (iMPC) navigation controller node for the mecanum robot.

This node drives the holonomic mecanum base toward a goal pose while respecting
velocity limits, arena walls, and dynamic obstacle half-planes. It runs the
OSQP solver generated offline by ``scripts/build_mpc_solver.py`` via CVXPYgen --
no CVXPY is used at runtime.

State  x = [px, py, theta]^T   (arena/map frame)
Control u = [vx, vy, omega]^T  (body frame: lateral, forward, yaw rate)

At each control tick the node:
  * builds a straight-line reference trajectory to the goal,
  * linearises the holonomic kinematics around the current heading (B(theta)),
  * encodes nearby obstacles as half-plane constraints,
  * warm-starts and calls the compiled QP,
  * publishes the first control as a TwistStamped on /cmd_vel.

If the compiled solver is unavailable the node still constructs but refuses to
solve, publishing zero velocity and logging a FATAL hint (degrade gracefully).
"""

import math
import os
import sys
from typing import List, Optional

import numpy as np
import rclpy
from geometry_msgs.msg import PoseStamped, Quaternion, TwistStamped
from nav_msgs.msg import Odometry
from rclpy.node import Node
from rclpy.qos import QoSHistoryPolicy, QoSProfile, QoSReliabilityPolicy
from vision_msgs.msg import Detection2DArray

# Shared QP definition (same module the offline generator used). The node
# rebuilds a structurally identical CVXPY problem and binds the compiled solver
# to it; CVXPYgen's cpg_solve needs this problem object as its param/var
# container (see mpc_problem.py for the full explanation).
from unibots_control.mpc_problem import build_problem

# ----------------------------------------------------------------------------
# Named constants (NO magic numbers).
# ----------------------------------------------------------------------------
N_STATES: int = 3
N_CONTROLS: int = 3
MAX_OBSTACLES: int = 6           # MUST match build_mpc_solver.py MAX_OBSTACLES.

QOS_DEPTH: int = 10

# Sentinel half-plane for unused obstacle slots: n=[1,0], d=-999 -> always met.
INACTIVE_NORMAL = (1.0, 0.0)
INACTIVE_D: float = -999.0

# Rate-limit (seconds) for repeated informational/warning logs.
LOG_THROTTLE_S: float = 2.0

# Topic names.
TOPIC_ODOM: str = "/odom/filtered"
TOPIC_TARGET: str = "/game/target"
TOPIC_OBSTACLES: str = "/vision/obstacles"
TOPIC_CMD_VEL: str = "/cmd_vel"

# Try to import the compiled solver generated by scripts/build_mpc_solver.py.
# The generated module exposes cpg_solve(prob, ...) plus a problem-data object
# whose .param_dict / .var_dict hold the runtime Parameter / Variable structs.
#
# CVXPYgen emits a self-contained `generated_solver/` directory (C sources + a
# compiled Python extension). build_mpc_solver.py writes it next to itself, i.e.
# in the package's scripts/ dir. Because the node runs from the installed/ symlink
# location, that directory is NOT on sys.path by default, so we proactively search
# the likely places and add the PARENT of `generated_solver` to sys.path before
# importing. Override with the UNIBOTS_SOLVER_DIR env var (set it to the directory
# that *contains* generated_solver).
def _candidate_solver_parents() -> List[str]:
    """Return directories that may contain a `generated_solver/` package."""
    here = os.path.dirname(os.path.abspath(__file__))      # .../unibots_control/unibots_control
    pkg_root = os.path.dirname(here)                        # .../unibots_control
    cwd = os.getcwd()
    candidates = [
        os.environ.get("UNIBOTS_SOLVER_DIR", ""),           # explicit override
        here,                                               # inside the python package
        os.path.join(pkg_root, "scripts"),                  # where build script writes it
        pkg_root,
        cwd,                                                # run-from-here convenience
        # When launched from the colcon workspace root (the usual case), the
        # build script's output lives under the source tree at
        # src/unibots_control/scripts/generated_solver. --symlink-install makes
        # __file__ resolve into build/, so we add this explicit workspace-relative
        # path too. (Avoids needing UNIBOTS_SOLVER_DIR for the common layout.)
        os.path.join(cwd, "src", "unibots_control", "scripts"),
    ]
    # De-duplicate while preserving order, dropping empties.
    seen: set = set()
    out: List[str] = []
    for c in candidates:
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


def _import_compiled_solver():
    """Locate and import the compiled CVXPYgen/OSQP solver.

    Returns (cpg_solve_callable_or_None, ok_bool, error_string).
    """
    for parent in _candidate_solver_parents():
        if os.path.isdir(os.path.join(parent, "generated_solver")):
            if parent not in sys.path:
                sys.path.insert(0, parent)
            break
    try:
        from generated_solver.cpg_solver import cpg_solve as _solve  # type: ignore
        import generated_solver.cpg_module as _mod  # type: ignore  # noqa: F401
        return _solve, True, ""
    except Exception as exc:  # ImportError or C-extension load failure.
        return None, False, str(exc)


cpg_solve, _SOLVER_IMPORT_OK, _SOLVER_IMPORT_ERR = _import_compiled_solver()


def compute_rotation_matrix(theta: float) -> np.ndarray:
    """Return the 3x3 body-to-world rotation B(theta) for holonomic kinematics.

    B maps body-frame velocities [vx, vy, omega] into world-frame state
    derivatives [pxdot, pydot, thetadot]:

        B(theta) = [[cos t, -sin t, 0],
                    [sin t,  cos t, 0],
                    [    0,      0, 1]]

    Args:
        theta: robot heading in the arena frame [rad].

    Returns:
        3x3 numpy array B(theta).
    """
    c = math.cos(theta)
    s = math.sin(theta)
    return np.array(
        [[c, -s, 0.0],
         [s,  c, 0.0],
         [0.0, 0.0, 1.0]],
        dtype=float,
    )


def yaw_from_quaternion(q: Quaternion) -> float:
    """Extract the yaw (heading) angle from a geometry_msgs Quaternion.

    Args:
        q: orientation quaternion.

    Returns:
        Yaw angle [rad] in (-pi, pi].
    """
    siny_cosp = 2.0 * (q.w * q.z + q.x * q.y)
    cosy_cosp = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
    return math.atan2(siny_cosp, cosy_cosp)


def wrap_angle(angle: float) -> float:
    """Wrap an angle to the interval (-pi, pi].

    Args:
        angle: input angle [rad].

    Returns:
        Equivalent angle in (-pi, pi].
    """
    return math.atan2(math.sin(angle), math.cos(angle))


class MpcControllerNode(Node):
    """ROS 2 node running the compiled iMPC QP to produce /cmd_vel commands."""

    def __init__(self) -> None:
        """Construct the node, declare params, set up I/O and the control timer."""
        super().__init__("mpc_controller_node")

        # --- Declare + read parameters at startup ----------------------------
        self.declare_parameter("dt", 0.05)
        self.declare_parameter("horizon_n", 10)
        self.declare_parameter("max_vx", 0.35)
        self.declare_parameter("max_vy", 0.45)
        self.declare_parameter("max_omega", 1.2)
        self.declare_parameter("arena_min", 0.15)
        self.declare_parameter("arena_max", 1.85)
        self.declare_parameter("goal_tolerance", 0.05)
        self.declare_parameter("control_frequency", 20.0)
        self.declare_parameter("obstacle_safety_radius", 0.25)

        self._dt: float = self.get_parameter("dt").value
        self._n: int = int(self.get_parameter("horizon_n").value)
        self._max_vx: float = self.get_parameter("max_vx").value
        self._max_vy: float = self.get_parameter("max_vy").value
        self._max_omega: float = self.get_parameter("max_omega").value
        self._arena_min: float = self.get_parameter("arena_min").value
        self._arena_max: float = self.get_parameter("arena_max").value
        self._goal_tolerance: float = self.get_parameter("goal_tolerance").value
        self._control_freq: float = self.get_parameter("control_frequency").value
        self._safety_radius: float = self.get_parameter("obstacle_safety_radius").value

        # --- Solver availability --------------------------------------------
        self._solver_available: bool = _SOLVER_IMPORT_OK
        if not self._solver_available:
            self.get_logger().fatal(
                "Compiled iMPC solver could not be imported (%s). "
                "Run 'python3 scripts/build_mpc_solver.py' on the dev machine "
                "and keep 'generated_solver/' next to the node. The node will "
                "publish ZERO velocity until then." % _SOLVER_IMPORT_ERR
            )
            self._problem = None
        else:
            # CVXPYgen's cpg_solver.py exposes only the cpg_solve FUNCTION, not a
            # Problem object. Rebuild a structurally identical CVXPY problem here
            # and register the compiled solver as its "CPG" solve method. The
            # param_dict / var_dict on this rebuilt problem are what cpg_solve
            # reads/writes; the numeric solve itself runs in the compiled C.
            try:
                self._problem = build_problem()
                self._problem.register_solve("CPG", cpg_solve)
                self.get_logger().info(
                    "Compiled iMPC solver loaded and bound to the rebuilt QP."
                )
            except Exception as exc:  # structure/version mismatch, etc.
                self._solver_available = False
                self._problem = None
                self.get_logger().fatal(
                    "Failed to bind compiled iMPC solver to the QP (%s). Did you "
                    "re-run scripts/build_mpc_solver.py after changing the QP "
                    "structure? Publishing ZERO velocity." % exc
                )

        # --- Runtime state ---------------------------------------------------
        self._current_pose: Optional[np.ndarray] = None   # [px, py, theta]
        self._goal: Optional[np.ndarray] = None           # [px, py, theta]
        self._obstacles: List[np.ndarray] = []            # list of [ox, oy, r]
        # Warm-start cache (controls over the horizon), zeros initially.
        self._prev_u: np.ndarray = np.zeros((N_CONTROLS, self._n))

        # --- QoS: RELIABLE, depth 10 ----------------------------------------
        qos = QoSProfile(
            reliability=QoSReliabilityPolicy.RELIABLE,
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=QOS_DEPTH,
        )

        # --- Subscriptions ---------------------------------------------------
        self.create_subscription(Odometry, TOPIC_ODOM, self._odom_cb, qos)
        self.create_subscription(PoseStamped, TOPIC_TARGET, self._target_cb, qos)
        self.create_subscription(
            Detection2DArray, TOPIC_OBSTACLES, self._obstacles_cb, qos
        )

        # --- Publisher -------------------------------------------------------
        self._cmd_pub = self.create_publisher(TwistStamped, TOPIC_CMD_VEL, qos)

        # --- Control loop timer (no while True + sleep) ----------------------
        timer_period = 1.0 / self._control_freq
        self.create_timer(timer_period, self._control_loop)

        self.get_logger().info(
            f"MpcControllerNode up: N={self._n}, dt={self._dt}, "
            f"freq={self._control_freq} Hz."
        )

        # --- Previous state cache for warm-starting the solver. Initialized to zeros.
        self._prev_x: np.ndarray = np.zeros((N_STATES, self._n + 1))

    # ------------------------------------------------------------------------
    # Subscription callbacks
    # ------------------------------------------------------------------------
    def _odom_cb(self, msg: Odometry) -> None:
        """Store current pose, extracting yaw from the odometry quaternion."""
        p = msg.pose.pose.position
        theta = yaw_from_quaternion(msg.pose.pose.orientation)
        self._current_pose = np.array([p.x, p.y, theta], dtype=float)

    def _target_cb(self, msg: PoseStamped) -> None:
        """Store the goal pose."""
        p = msg.pose.position
        theta = yaw_from_quaternion(msg.pose.orientation)
        self._goal = np.array([p.x, p.y, theta], dtype=float)

    def _obstacles_cb(self, msg: Detection2DArray) -> None:
        """Store detected obstacles from a vision_msgs/Detection2DArray.

        Field interpretation (documented mapping; we use Detection2DArray per
        spec even though unibots_msgs also defines an ObstacleArray):
            detection.bbox.center.position.x -> obstacle world_x [m]
            detection.bbox.center.position.y -> obstacle world_y [m]
            detection.bbox.size_x            -> obstacle radius   [m]
        """
        obstacles: List[np.ndarray] = []
        for det in msg.detections:
            ox = det.bbox.center.position.x
            oy = det.bbox.center.position.y
            radius = det.bbox.size_x
            obstacles.append(np.array([ox, oy, radius], dtype=float))
        self._obstacles = obstacles

    # ------------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------------
    def _publish_zero(self) -> None:
        """Publish a zero-velocity TwistStamped (safe stop)."""
        msg = TwistStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        self._cmd_pub.publish(msg)

    def _build_reference(self) -> np.ndarray:
        """Build a straight-line reference trajectory current -> goal.

        Interpolates px, py linearly and theta along the shortest angular path
        over N+1 horizon points.

        Returns:
            (3, N+1) reference state trajectory.
        """
        assert self._current_pose is not None and self._goal is not None
        ref = np.zeros((N_STATES, self._n + 1), dtype=float)
        start = self._current_pose
        goal = self._goal
        # Shortest angular path for heading.
        dtheta = wrap_angle(goal[2] - start[2])
        for k in range(self._n + 1):
            alpha = k / float(self._n)
            ref[0, k] = start[0] + alpha * (goal[0] - start[0])
            ref[1, k] = start[1] + alpha * (goal[1] - start[1])
            ref[2, k] = wrap_angle(start[2] + alpha * dtheta)
        return ref

    def _build_obstacle_halfplanes(self):
        """Build padded obstacle half-planes (n, d) for the current pose.

        For an obstacle at (ox, oy) relative to the robot position p:
            n = (p - obs) / ||p - obs||      (unit normal pointing away from obs)
            d = n . obs + safety_radius      (clearance offset)
        Constraint enforced in the QP:  n^T p_k >= d.

        Returns:
            Tuple (normals, offsets):
              normals: list of MAX_OBSTACLES np.array(2,)
              offsets: list of MAX_OBSTACLES float
            Unused slots use n=[1,0], d=-999 (always satisfied).
        """
        assert self._current_pose is not None
        pos = self._current_pose[0:2]
        normals: List[np.ndarray] = []
        offsets: List[float] = []

        for obs in self._obstacles[:MAX_OBSTACLES]:
            obs_xy = obs[0:2]
            diff = pos - obs_xy
            dist = float(np.linalg.norm(diff))
            if dist < 1e-6:
                # Degenerate (on top of obstacle): use an arbitrary push-out.
                n = np.array(INACTIVE_NORMAL, dtype=float)
                d = INACTIVE_D
            else:
                n = diff / dist
                # Obstacle's own radius folds into the per-obstacle clearance.
                clearance = self._safety_radius + float(obs[2])
                d = float(np.dot(n, obs_xy) + clearance)
            normals.append(n)
            offsets.append(d)

        # Pad to EXACTLY MAX_OBSTACLES inactive slots.
        while len(normals) < MAX_OBSTACLES:
            normals.append(np.array(INACTIVE_NORMAL, dtype=float))
            offsets.append(INACTIVE_D)

        return normals, offsets

    def _set_param(self, name: str, value: np.ndarray) -> None:
        """Set a value on a compiled-problem Parameter by name.

        Uses the CVXPY Problem object bound to the generated solver; setting
        ``.value`` propagates into the compiled OSQP data on the next solve.
        """
        self._problem.param_dict[name].value = value

    # ------------------------------------------------------------------------
    # Control loop
    # ------------------------------------------------------------------------
    def _control_loop(self) -> None:
        """Main MPC control tick (runs on the control-frequency timer)."""
        # If the compiled solver is unavailable, fail safe.
        if not self._solver_available:
            self._publish_zero()
            self.get_logger().warn(
                "iMPC solver unavailable -> publishing zero. "
                "Run scripts/build_mpc_solver.py.",
                throttle_duration_sec=LOG_THROTTLE_S,
            )
            return

        # Step 1: no goal or no pose -> publish zero, return.
        if self._current_pose is None or self._goal is None:
            self._publish_zero()
            return

        # Step 2: distance to goal; if within tolerance, stop and log arrival.
        dist_to_goal = float(
            np.linalg.norm(self._goal[0:2] - self._current_pose[0:2])
        )
        if dist_to_goal < self._goal_tolerance:
            self._publish_zero()
            self.get_logger().info(
                "Goal reached (within tolerance) -> holding.",
                throttle_duration_sec=LOG_THROTTLE_S,
            )
            return

        # Step 3: reference trajectory (straight line, shortest-path heading).
        x_ref = self._build_reference()

        # Step 4: True Iterative Linearization
        # Use the predicted theta trajectory from the LAST solve to linearize
        # the current prediction horizon.
        for k in range(self._n):
            # If we have a valid previous prediction, use its theta_k. 
            # Otherwise, fallback to current theta.
            if np.any(self._prev_x):
                theta_k = float(self._prev_x[2, k])
            else:
                theta_k = float(self._current_pose[2])
                
            B_k = compute_rotation_matrix(theta_k)
            self._set_param(f"B_{k}", B_k)

        # Step 5: obstacle half-planes (padded to MAX_OBSTACLES).
        normals, offsets = self._build_obstacle_halfplanes()
        # The same set of half-planes is applied at every horizon point because
        # obstacles are treated as static over the (short) horizon.
        for k in range(self._n + 1):
            for i in range(MAX_OBSTACLES):
                self._set_param(f"n_{k}_{i}", normals[i])
                # d_{k}_{i} is a SCALAR cvxpy Parameter (shape ()), so assign a
                # plain float -- a shape-(1,) array is rejected as invalid dims.
                self._set_param(f"d_{k}_{i}", float(offsets[i]))

        # Set state params.
        self._set_param("x0", self._current_pose.astype(float))
        self._set_param("x_ref", x_ref)

        # Step 6: warm-start by loading the previous control solution.
        self._problem.var_dict["u"].value = self._prev_u

        # Step 7: call the compiled solver and check status. Using the registered
        # "CPG" method runs the compiled OSQP code (no CVXPY re-canonicalisation)
        # and populates problem.status / var_dict.
        try:
            self._problem.solve(method="CPG")
        except Exception as exc:  # defensive: never let a solver fault crash us
            self.get_logger().error(
                f"Compiled solver raised: {exc}. Publishing zero.",
                throttle_duration_sec=LOG_THROTTLE_S,
            )
            self._publish_zero()
            return

        status = self._problem.status

        # Step 8: extract and publish, or fail safe on infeasibility.
        if status in ("optimal", "optimal_inaccurate"):
            u_sol = self._problem.var_dict["u"].value
            x_sol = self._problem.var_dict["x"].value
            
            if u_sol is None or x_sol is None:
                self._publish_zero()
                return
            
            u0 = u_sol[:, 0]
            self._publish_cmd(u0)
            
            # Step 9: store solution for next warm-start and relinearization.
            self._prev_u = np.asarray(u_sol, dtype=float)
            self._prev_x = np.asarray(x_sol, dtype=float)

    def _publish_cmd(self, u0: np.ndarray) -> None:
        """Publish the first control as a TwistStamped.

        Body-frame mapping:
            u0[0] = vx (body lateral) -> twist.linear.x
            u0[1] = vy (body forward) -> twist.linear.y
            u0[2] = omega (yaw rate)  -> twist.angular.z
        """
        vx = float(np.clip(u0[0], -self._max_vx, self._max_vx))
        vy = float(np.clip(u0[1], -self._max_vy, self._max_vy))
        omega = float(np.clip(u0[2], -self._max_omega, self._max_omega))

        msg = TwistStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.twist.linear.x = vx
        msg.twist.linear.y = vy
        msg.twist.angular.z = omega
        self._cmd_pub.publish(msg)


def main(args=None) -> None:
    """Entry point: init rclpy, spin the MPC controller node, clean up."""
    rclpy.init(args=args)
    node = MpcControllerNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
