
/*
Auto-generated by CVXPYgen on June 16, 2026 at 23:32:42
Content: Example program for updating parameters, solving, and inspecting the result
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_x_ref(0, 1.00000000000000000000);
  cpg_update_x0(0, 1.00000000000000000000);
  cpg_update_B_0(0, 1.00000000000000000000);
  cpg_update_B_1(0, 1.00000000000000000000);
  cpg_update_B_2(0, 1.00000000000000000000);
  cpg_update_B_3(0, 1.00000000000000000000);
  cpg_update_B_4(0, 1.00000000000000000000);
  cpg_update_B_5(0, 1.00000000000000000000);
  cpg_update_B_6(0, 1.00000000000000000000);
  cpg_update_B_7(0, 1.00000000000000000000);
  cpg_update_B_8(0, 1.00000000000000000000);
  cpg_update_B_9(0, 1.00000000000000000000);
  cpg_update_d_0_0(1.00000000000000000000);
  cpg_update_n_0_0(0, 1.00000000000000000000);
  cpg_update_d_0_1(1.00000000000000000000);
  cpg_update_n_0_1(0, 1.00000000000000000000);
  cpg_update_d_0_2(1.00000000000000000000);
  cpg_update_n_0_2(0, 1.00000000000000000000);
  cpg_update_d_0_3(1.00000000000000000000);
  cpg_update_n_0_3(0, 1.00000000000000000000);
  cpg_update_d_0_4(1.00000000000000000000);
  cpg_update_n_0_4(0, 1.00000000000000000000);
  cpg_update_d_0_5(1.00000000000000000000);
  cpg_update_n_0_5(0, 1.00000000000000000000);
  cpg_update_d_1_0(1.00000000000000000000);
  cpg_update_n_1_0(0, 1.00000000000000000000);
  cpg_update_d_1_1(1.00000000000000000000);
  cpg_update_n_1_1(0, 1.00000000000000000000);
  cpg_update_d_1_2(1.00000000000000000000);
  cpg_update_n_1_2(0, 1.00000000000000000000);
  cpg_update_d_1_3(1.00000000000000000000);
  cpg_update_n_1_3(0, 1.00000000000000000000);
  cpg_update_d_1_4(1.00000000000000000000);
  cpg_update_n_1_4(0, 1.00000000000000000000);
  cpg_update_d_1_5(1.00000000000000000000);
  cpg_update_n_1_5(0, 1.00000000000000000000);
  cpg_update_d_2_0(1.00000000000000000000);
  cpg_update_n_2_0(0, 1.00000000000000000000);
  cpg_update_d_2_1(1.00000000000000000000);
  cpg_update_n_2_1(0, 1.00000000000000000000);
  cpg_update_d_2_2(1.00000000000000000000);
  cpg_update_n_2_2(0, 1.00000000000000000000);
  cpg_update_d_2_3(1.00000000000000000000);
  cpg_update_n_2_3(0, 1.00000000000000000000);
  cpg_update_d_2_4(1.00000000000000000000);
  cpg_update_n_2_4(0, 1.00000000000000000000);
  cpg_update_d_2_5(1.00000000000000000000);
  cpg_update_n_2_5(0, 1.00000000000000000000);
  cpg_update_d_3_0(1.00000000000000000000);
  cpg_update_n_3_0(0, 1.00000000000000000000);
  cpg_update_d_3_1(1.00000000000000000000);
  cpg_update_n_3_1(0, 1.00000000000000000000);
  cpg_update_d_3_2(1.00000000000000000000);
  cpg_update_n_3_2(0, 1.00000000000000000000);
  cpg_update_d_3_3(1.00000000000000000000);
  cpg_update_n_3_3(0, 1.00000000000000000000);
  cpg_update_d_3_4(1.00000000000000000000);
  cpg_update_n_3_4(0, 1.00000000000000000000);
  cpg_update_d_3_5(1.00000000000000000000);
  cpg_update_n_3_5(0, 1.00000000000000000000);
  cpg_update_d_4_0(1.00000000000000000000);
  cpg_update_n_4_0(0, 1.00000000000000000000);
  cpg_update_d_4_1(1.00000000000000000000);
  cpg_update_n_4_1(0, 1.00000000000000000000);
  cpg_update_d_4_2(1.00000000000000000000);
  cpg_update_n_4_2(0, 1.00000000000000000000);
  cpg_update_d_4_3(1.00000000000000000000);
  cpg_update_n_4_3(0, 1.00000000000000000000);
  cpg_update_d_4_4(1.00000000000000000000);
  cpg_update_n_4_4(0, 1.00000000000000000000);
  cpg_update_d_4_5(1.00000000000000000000);
  cpg_update_n_4_5(0, 1.00000000000000000000);
  cpg_update_d_5_0(1.00000000000000000000);
  cpg_update_n_5_0(0, 1.00000000000000000000);
  cpg_update_d_5_1(1.00000000000000000000);
  cpg_update_n_5_1(0, 1.00000000000000000000);
  cpg_update_d_5_2(1.00000000000000000000);
  cpg_update_n_5_2(0, 1.00000000000000000000);
  cpg_update_d_5_3(1.00000000000000000000);
  cpg_update_n_5_3(0, 1.00000000000000000000);
  cpg_update_d_5_4(1.00000000000000000000);
  cpg_update_n_5_4(0, 1.00000000000000000000);
  cpg_update_d_5_5(1.00000000000000000000);
  cpg_update_n_5_5(0, 1.00000000000000000000);
  cpg_update_d_6_0(1.00000000000000000000);
  cpg_update_n_6_0(0, 1.00000000000000000000);
  cpg_update_d_6_1(1.00000000000000000000);
  cpg_update_n_6_1(0, 1.00000000000000000000);
  cpg_update_d_6_2(1.00000000000000000000);
  cpg_update_n_6_2(0, 1.00000000000000000000);
  cpg_update_d_6_3(1.00000000000000000000);
  cpg_update_n_6_3(0, 1.00000000000000000000);
  cpg_update_d_6_4(1.00000000000000000000);
  cpg_update_n_6_4(0, 1.00000000000000000000);
  cpg_update_d_6_5(1.00000000000000000000);
  cpg_update_n_6_5(0, 1.00000000000000000000);
  cpg_update_d_7_0(1.00000000000000000000);
  cpg_update_n_7_0(0, 1.00000000000000000000);
  cpg_update_d_7_1(1.00000000000000000000);
  cpg_update_n_7_1(0, 1.00000000000000000000);
  cpg_update_d_7_2(1.00000000000000000000);
  cpg_update_n_7_2(0, 1.00000000000000000000);
  cpg_update_d_7_3(1.00000000000000000000);
  cpg_update_n_7_3(0, 1.00000000000000000000);
  cpg_update_d_7_4(1.00000000000000000000);
  cpg_update_n_7_4(0, 1.00000000000000000000);
  cpg_update_d_7_5(1.00000000000000000000);
  cpg_update_n_7_5(0, 1.00000000000000000000);
  cpg_update_d_8_0(1.00000000000000000000);
  cpg_update_n_8_0(0, 1.00000000000000000000);
  cpg_update_d_8_1(1.00000000000000000000);
  cpg_update_n_8_1(0, 1.00000000000000000000);
  cpg_update_d_8_2(1.00000000000000000000);
  cpg_update_n_8_2(0, 1.00000000000000000000);
  cpg_update_d_8_3(1.00000000000000000000);
  cpg_update_n_8_3(0, 1.00000000000000000000);
  cpg_update_d_8_4(1.00000000000000000000);
  cpg_update_n_8_4(0, 1.00000000000000000000);
  cpg_update_d_8_5(1.00000000000000000000);
  cpg_update_n_8_5(0, 1.00000000000000000000);
  cpg_update_d_9_0(1.00000000000000000000);
  cpg_update_n_9_0(0, 1.00000000000000000000);
  cpg_update_d_9_1(1.00000000000000000000);
  cpg_update_n_9_1(0, 1.00000000000000000000);
  cpg_update_d_9_2(1.00000000000000000000);
  cpg_update_n_9_2(0, 1.00000000000000000000);
  cpg_update_d_9_3(1.00000000000000000000);
  cpg_update_n_9_3(0, 1.00000000000000000000);
  cpg_update_d_9_4(1.00000000000000000000);
  cpg_update_n_9_4(0, 1.00000000000000000000);
  cpg_update_d_9_5(1.00000000000000000000);
  cpg_update_n_9_5(0, 1.00000000000000000000);
  cpg_update_d_10_0(1.00000000000000000000);
  cpg_update_n_10_0(0, 1.00000000000000000000);
  cpg_update_d_10_1(1.00000000000000000000);
  cpg_update_n_10_1(0, 1.00000000000000000000);
  cpg_update_d_10_2(1.00000000000000000000);
  cpg_update_n_10_2(0, 1.00000000000000000000);
  cpg_update_d_10_3(1.00000000000000000000);
  cpg_update_n_10_3(0, 1.00000000000000000000);
  cpg_update_d_10_4(1.00000000000000000000);
  cpg_update_n_10_4(0, 1.00000000000000000000);
  cpg_update_d_10_5(1.00000000000000000000);
  cpg_update_n_10_5(0, 1.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<33; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<30; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<44; i++) {
    printf("s_wall[%d] = %f\n", i, CPG_Result.prim->s_wall[i]);
  }
  for(i=0; i<66; i++) {
    printf("s_obs[%d] = %f\n", i, CPG_Result.prim->s_obs[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  printf("d3 = %f\n", CPG_Result.dual->d3);
  printf("d4 = %f\n", CPG_Result.dual->d4);
  for(i=0; i<3; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  printf("d6 = %f\n", CPG_Result.dual->d6);
  printf("d7 = %f\n", CPG_Result.dual->d7);
  printf("d8 = %f\n", CPG_Result.dual->d8);
  for(i=0; i<3; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  printf("d10 = %f\n", CPG_Result.dual->d10);
  printf("d11 = %f\n", CPG_Result.dual->d11);
  printf("d12 = %f\n", CPG_Result.dual->d12);
  for(i=0; i<3; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  printf("d14 = %f\n", CPG_Result.dual->d14);
  printf("d15 = %f\n", CPG_Result.dual->d15);
  printf("d16 = %f\n", CPG_Result.dual->d16);
  for(i=0; i<3; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  printf("d18 = %f\n", CPG_Result.dual->d18);
  printf("d19 = %f\n", CPG_Result.dual->d19);
  printf("d20 = %f\n", CPG_Result.dual->d20);
  for(i=0; i<3; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  printf("d22 = %f\n", CPG_Result.dual->d22);
  printf("d23 = %f\n", CPG_Result.dual->d23);
  printf("d24 = %f\n", CPG_Result.dual->d24);
  for(i=0; i<3; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  printf("d26 = %f\n", CPG_Result.dual->d26);
  printf("d27 = %f\n", CPG_Result.dual->d27);
  printf("d28 = %f\n", CPG_Result.dual->d28);
  for(i=0; i<3; i++) {
    printf("d29[%d] = %f\n", i, CPG_Result.dual->d29[i]);
  }
  printf("d30 = %f\n", CPG_Result.dual->d30);
  printf("d31 = %f\n", CPG_Result.dual->d31);
  printf("d32 = %f\n", CPG_Result.dual->d32);
  for(i=0; i<3; i++) {
    printf("d33[%d] = %f\n", i, CPG_Result.dual->d33[i]);
  }
  printf("d34 = %f\n", CPG_Result.dual->d34);
  printf("d35 = %f\n", CPG_Result.dual->d35);
  printf("d36 = %f\n", CPG_Result.dual->d36);
  for(i=0; i<3; i++) {
    printf("d37[%d] = %f\n", i, CPG_Result.dual->d37[i]);
  }
  printf("d38 = %f\n", CPG_Result.dual->d38);
  printf("d39 = %f\n", CPG_Result.dual->d39);
  printf("d40 = %f\n", CPG_Result.dual->d40);
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  printf("d43 = %f\n", CPG_Result.dual->d43);
  printf("d44 = %f\n", CPG_Result.dual->d44);
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  printf("d47 = %f\n", CPG_Result.dual->d47);
  printf("d48 = %f\n", CPG_Result.dual->d48);
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);
  printf("d51 = %f\n", CPG_Result.dual->d51);
  printf("d52 = %f\n", CPG_Result.dual->d52);
  printf("d53 = %f\n", CPG_Result.dual->d53);
  printf("d54 = %f\n", CPG_Result.dual->d54);
  printf("d55 = %f\n", CPG_Result.dual->d55);
  printf("d56 = %f\n", CPG_Result.dual->d56);
  printf("d57 = %f\n", CPG_Result.dual->d57);
  printf("d58 = %f\n", CPG_Result.dual->d58);
  printf("d59 = %f\n", CPG_Result.dual->d59);
  printf("d60 = %f\n", CPG_Result.dual->d60);
  printf("d61 = %f\n", CPG_Result.dual->d61);
  printf("d62 = %f\n", CPG_Result.dual->d62);
  printf("d63 = %f\n", CPG_Result.dual->d63);
  printf("d64 = %f\n", CPG_Result.dual->d64);
  printf("d65 = %f\n", CPG_Result.dual->d65);
  printf("d66 = %f\n", CPG_Result.dual->d66);
  printf("d67 = %f\n", CPG_Result.dual->d67);
  printf("d68 = %f\n", CPG_Result.dual->d68);
  printf("d69 = %f\n", CPG_Result.dual->d69);
  printf("d70 = %f\n", CPG_Result.dual->d70);
  printf("d71 = %f\n", CPG_Result.dual->d71);
  printf("d72 = %f\n", CPG_Result.dual->d72);
  printf("d73 = %f\n", CPG_Result.dual->d73);
  printf("d74 = %f\n", CPG_Result.dual->d74);
  printf("d75 = %f\n", CPG_Result.dual->d75);
  printf("d76 = %f\n", CPG_Result.dual->d76);
  printf("d77 = %f\n", CPG_Result.dual->d77);
  printf("d78 = %f\n", CPG_Result.dual->d78);
  printf("d79 = %f\n", CPG_Result.dual->d79);
  printf("d80 = %f\n", CPG_Result.dual->d80);
  printf("d81 = %f\n", CPG_Result.dual->d81);
  printf("d82 = %f\n", CPG_Result.dual->d82);
  printf("d83 = %f\n", CPG_Result.dual->d83);
  printf("d84 = %f\n", CPG_Result.dual->d84);
  printf("d85 = %f\n", CPG_Result.dual->d85);
  printf("d86 = %f\n", CPG_Result.dual->d86);
  printf("d87 = %f\n", CPG_Result.dual->d87);
  printf("d88 = %f\n", CPG_Result.dual->d88);
  printf("d89 = %f\n", CPG_Result.dual->d89);
  printf("d90 = %f\n", CPG_Result.dual->d90);
  printf("d91 = %f\n", CPG_Result.dual->d91);
  printf("d92 = %f\n", CPG_Result.dual->d92);
  printf("d93 = %f\n", CPG_Result.dual->d93);
  printf("d94 = %f\n", CPG_Result.dual->d94);
  printf("d95 = %f\n", CPG_Result.dual->d95);
  printf("d96 = %f\n", CPG_Result.dual->d96);
  printf("d97 = %f\n", CPG_Result.dual->d97);
  printf("d98 = %f\n", CPG_Result.dual->d98);
  printf("d99 = %f\n", CPG_Result.dual->d99);
  printf("d100 = %f\n", CPG_Result.dual->d100);
  printf("d101 = %f\n", CPG_Result.dual->d101);
  printf("d102 = %f\n", CPG_Result.dual->d102);
  printf("d103 = %f\n", CPG_Result.dual->d103);
  printf("d104 = %f\n", CPG_Result.dual->d104);
  printf("d105 = %f\n", CPG_Result.dual->d105);
  printf("d106 = %f\n", CPG_Result.dual->d106);
  printf("d107 = %f\n", CPG_Result.dual->d107);
  printf("d108 = %f\n", CPG_Result.dual->d108);
  printf("d109 = %f\n", CPG_Result.dual->d109);
  printf("d110 = %f\n", CPG_Result.dual->d110);
  printf("d111 = %f\n", CPG_Result.dual->d111);
  printf("d112 = %f\n", CPG_Result.dual->d112);
  printf("d113 = %f\n", CPG_Result.dual->d113);
  printf("d114 = %f\n", CPG_Result.dual->d114);
  printf("d115 = %f\n", CPG_Result.dual->d115);
  printf("d116 = %f\n", CPG_Result.dual->d116);
  printf("d117 = %f\n", CPG_Result.dual->d117);
  printf("d118 = %f\n", CPG_Result.dual->d118);
  printf("d119 = %f\n", CPG_Result.dual->d119);
  printf("d120 = %f\n", CPG_Result.dual->d120);
  printf("d121 = %f\n", CPG_Result.dual->d121);
  printf("d122 = %f\n", CPG_Result.dual->d122);
  printf("d123 = %f\n", CPG_Result.dual->d123);
  printf("d124 = %f\n", CPG_Result.dual->d124);
  printf("d125 = %f\n", CPG_Result.dual->d125);
  printf("d126 = %f\n", CPG_Result.dual->d126);
  printf("d127 = %f\n", CPG_Result.dual->d127);
  printf("d128 = %f\n", CPG_Result.dual->d128);
  printf("d129 = %f\n", CPG_Result.dual->d129);
  printf("d130 = %f\n", CPG_Result.dual->d130);
  printf("d131 = %f\n", CPG_Result.dual->d131);
  printf("d132 = %f\n", CPG_Result.dual->d132);
  printf("d133 = %f\n", CPG_Result.dual->d133);
  printf("d134 = %f\n", CPG_Result.dual->d134);
  printf("d135 = %f\n", CPG_Result.dual->d135);
  printf("d136 = %f\n", CPG_Result.dual->d136);
  printf("d137 = %f\n", CPG_Result.dual->d137);
  printf("d138 = %f\n", CPG_Result.dual->d138);
  printf("d139 = %f\n", CPG_Result.dual->d139);
  printf("d140 = %f\n", CPG_Result.dual->d140);
  printf("d141 = %f\n", CPG_Result.dual->d141);
  printf("d142 = %f\n", CPG_Result.dual->d142);
  printf("d143 = %f\n", CPG_Result.dual->d143);
  printf("d144 = %f\n", CPG_Result.dual->d144);
  printf("d145 = %f\n", CPG_Result.dual->d145);
  printf("d146 = %f\n", CPG_Result.dual->d146);
  printf("d147 = %f\n", CPG_Result.dual->d147);
  printf("d148 = %f\n", CPG_Result.dual->d148);
  printf("d149 = %f\n", CPG_Result.dual->d149);
  printf("d150 = %f\n", CPG_Result.dual->d150);


  return 0;

}
