
/*
Auto-generated by CVXPYgen on June 22, 2026 at 18:17:08
Content: Function definitions
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.q = 1;
}

void cpg_update_x0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+33] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

void cpg_update_B_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+36] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+45] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+54] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+63] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+72] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+81] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+90] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+99] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+108] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+117] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_0(cpg_float val){
  cpg_params_vec[126] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+127] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_1(cpg_float val){
  cpg_params_vec[129] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+130] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_2(cpg_float val){
  cpg_params_vec[132] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+133] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_3(cpg_float val){
  cpg_params_vec[135] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+136] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_4(cpg_float val){
  cpg_params_vec[138] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+139] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_0_5(cpg_float val){
  cpg_params_vec[141] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_0_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+142] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_0(cpg_float val){
  cpg_params_vec[144] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+145] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_1(cpg_float val){
  cpg_params_vec[147] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+148] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_2(cpg_float val){
  cpg_params_vec[150] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+151] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_3(cpg_float val){
  cpg_params_vec[153] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+154] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_4(cpg_float val){
  cpg_params_vec[156] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+157] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_1_5(cpg_float val){
  cpg_params_vec[159] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_1_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+160] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_0(cpg_float val){
  cpg_params_vec[162] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+163] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_1(cpg_float val){
  cpg_params_vec[165] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+166] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_2(cpg_float val){
  cpg_params_vec[168] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+169] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_3(cpg_float val){
  cpg_params_vec[171] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+172] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_4(cpg_float val){
  cpg_params_vec[174] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+175] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_2_5(cpg_float val){
  cpg_params_vec[177] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_2_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+178] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_0(cpg_float val){
  cpg_params_vec[180] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+181] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_1(cpg_float val){
  cpg_params_vec[183] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+184] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_2(cpg_float val){
  cpg_params_vec[186] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+187] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_3(cpg_float val){
  cpg_params_vec[189] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+190] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_4(cpg_float val){
  cpg_params_vec[192] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+193] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_3_5(cpg_float val){
  cpg_params_vec[195] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_3_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+196] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_0(cpg_float val){
  cpg_params_vec[198] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+199] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_1(cpg_float val){
  cpg_params_vec[201] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+202] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_2(cpg_float val){
  cpg_params_vec[204] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+205] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_3(cpg_float val){
  cpg_params_vec[207] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+208] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_4(cpg_float val){
  cpg_params_vec[210] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+211] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_4_5(cpg_float val){
  cpg_params_vec[213] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_4_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+214] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_0(cpg_float val){
  cpg_params_vec[216] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+217] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_1(cpg_float val){
  cpg_params_vec[219] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+220] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_2(cpg_float val){
  cpg_params_vec[222] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+223] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_3(cpg_float val){
  cpg_params_vec[225] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+226] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_4(cpg_float val){
  cpg_params_vec[228] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+229] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_5_5(cpg_float val){
  cpg_params_vec[231] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_5_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+232] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_0(cpg_float val){
  cpg_params_vec[234] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+235] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_1(cpg_float val){
  cpg_params_vec[237] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+238] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_2(cpg_float val){
  cpg_params_vec[240] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+241] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_3(cpg_float val){
  cpg_params_vec[243] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+244] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_4(cpg_float val){
  cpg_params_vec[246] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+247] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_6_5(cpg_float val){
  cpg_params_vec[249] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_6_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+250] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_0(cpg_float val){
  cpg_params_vec[252] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+253] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_1(cpg_float val){
  cpg_params_vec[255] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+256] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_2(cpg_float val){
  cpg_params_vec[258] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+259] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_3(cpg_float val){
  cpg_params_vec[261] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+262] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_4(cpg_float val){
  cpg_params_vec[264] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+265] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_7_5(cpg_float val){
  cpg_params_vec[267] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_7_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+268] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_0(cpg_float val){
  cpg_params_vec[270] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+271] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_1(cpg_float val){
  cpg_params_vec[273] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+274] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_2(cpg_float val){
  cpg_params_vec[276] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+277] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_3(cpg_float val){
  cpg_params_vec[279] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+280] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_4(cpg_float val){
  cpg_params_vec[282] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+283] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_8_5(cpg_float val){
  cpg_params_vec[285] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_8_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+286] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_0(cpg_float val){
  cpg_params_vec[288] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+289] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_1(cpg_float val){
  cpg_params_vec[291] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+292] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_2(cpg_float val){
  cpg_params_vec[294] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+295] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_3(cpg_float val){
  cpg_params_vec[297] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+298] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_4(cpg_float val){
  cpg_params_vec[300] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+301] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_9_5(cpg_float val){
  cpg_params_vec[303] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_9_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+304] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_0(cpg_float val){
  cpg_params_vec[306] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+307] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_1(cpg_float val){
  cpg_params_vec[309] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+310] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_2(cpg_float val){
  cpg_params_vec[312] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+313] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_3(cpg_float val){
  cpg_params_vec[315] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+316] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_4(cpg_float val){
  cpg_params_vec[318] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+319] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_d_10_5(cpg_float val){
  cpg_params_vec[321] = val;
  Canon_Outdated.u = 1;
}

void cpg_update_n_10_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+322] = val;
  Canon_Outdated.A = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_q(){
  for(i=0; i<252; i++){
    Canon_Params.q[i] = 0;
    for(j=canon_q_map.p[i]; j<canon_q_map.p[i+1]; j++){
      Canon_Params.q[i] += canon_q_map.x[j]*cpg_params_vec[canon_q_map.i[j]];
    }
  }
}

void cpg_canonicalize_A(){
  for(i=0; i<780; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_l(){
  for(i=0; i<126; i++){
    Canon_Params.l[i] = 0;
    for(j=canon_l_map.p[i]; j<canon_l_map.p[i+1]; j++){
      Canon_Params.l[i] += canon_l_map.x[j]*cpg_params_vec[canon_l_map.i[j]];
    }
  }
}

void cpg_canonicalize_u(){
  for(i=0; i<348; i++){
    Canon_Params.u[i] = 0;
    for(j=canon_u_map.p[i]; j<canon_u_map.p[i+1]; j++){
      Canon_Params.u[i] += canon_u_map.x[j]*cpg_params_vec[canon_u_map.i[j]];
    }
  }
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d2 = sol_y[194];
  CPG_Dual.d3 = sol_y[197];
  CPG_Dual.d4 = sol_y[200];
  CPG_Dual.d6 = sol_y[203];
  CPG_Dual.d7 = sol_y[206];
  CPG_Dual.d8 = sol_y[209];
  CPG_Dual.d10 = sol_y[212];
  CPG_Dual.d11 = sol_y[215];
  CPG_Dual.d12 = sol_y[218];
  CPG_Dual.d14 = sol_y[221];
  CPG_Dual.d15 = sol_y[224];
  CPG_Dual.d16 = sol_y[227];
  CPG_Dual.d18 = sol_y[230];
  CPG_Dual.d19 = sol_y[233];
  CPG_Dual.d20 = sol_y[236];
  CPG_Dual.d22 = sol_y[239];
  CPG_Dual.d23 = sol_y[242];
  CPG_Dual.d24 = sol_y[245];
  CPG_Dual.d26 = sol_y[248];
  CPG_Dual.d27 = sol_y[251];
  CPG_Dual.d28 = sol_y[254];
  CPG_Dual.d30 = sol_y[257];
  CPG_Dual.d31 = sol_y[260];
  CPG_Dual.d32 = sol_y[263];
  CPG_Dual.d34 = sol_y[266];
  CPG_Dual.d35 = sol_y[269];
  CPG_Dual.d36 = sol_y[272];
  CPG_Dual.d38 = sol_y[275];
  CPG_Dual.d39 = sol_y[278];
  CPG_Dual.d40 = sol_y[281];
  CPG_Dual.d41 = sol_y[282];
  CPG_Dual.d42 = sol_y[283];
  CPG_Dual.d43 = sol_y[284];
  CPG_Dual.d44 = sol_y[285];
  CPG_Dual.d45 = sol_y[286];
  CPG_Dual.d46 = sol_y[287];
  CPG_Dual.d47 = sol_y[288];
  CPG_Dual.d48 = sol_y[289];
  CPG_Dual.d49 = sol_y[290];
  CPG_Dual.d50 = sol_y[291];
  CPG_Dual.d51 = sol_y[292];
  CPG_Dual.d52 = sol_y[293];
  CPG_Dual.d53 = sol_y[294];
  CPG_Dual.d54 = sol_y[295];
  CPG_Dual.d55 = sol_y[296];
  CPG_Dual.d56 = sol_y[297];
  CPG_Dual.d57 = sol_y[298];
  CPG_Dual.d58 = sol_y[299];
  CPG_Dual.d59 = sol_y[300];
  CPG_Dual.d60 = sol_y[301];
  CPG_Dual.d61 = sol_y[302];
  CPG_Dual.d62 = sol_y[303];
  CPG_Dual.d63 = sol_y[304];
  CPG_Dual.d64 = sol_y[305];
  CPG_Dual.d65 = sol_y[306];
  CPG_Dual.d66 = sol_y[307];
  CPG_Dual.d67 = sol_y[308];
  CPG_Dual.d68 = sol_y[309];
  CPG_Dual.d69 = sol_y[310];
  CPG_Dual.d70 = sol_y[311];
  CPG_Dual.d71 = sol_y[312];
  CPG_Dual.d72 = sol_y[313];
  CPG_Dual.d73 = sol_y[314];
  CPG_Dual.d74 = sol_y[315];
  CPG_Dual.d75 = sol_y[316];
  CPG_Dual.d76 = sol_y[317];
  CPG_Dual.d77 = sol_y[318];
  CPG_Dual.d78 = sol_y[319];
  CPG_Dual.d79 = sol_y[320];
  CPG_Dual.d80 = sol_y[321];
  CPG_Dual.d81 = sol_y[322];
  CPG_Dual.d82 = sol_y[323];
  CPG_Dual.d83 = sol_y[324];
  CPG_Dual.d84 = sol_y[325];
  CPG_Dual.d85 = sol_y[326];
  CPG_Dual.d86 = sol_y[327];
  CPG_Dual.d87 = sol_y[328];
  CPG_Dual.d88 = sol_y[329];
  CPG_Dual.d89 = sol_y[330];
  CPG_Dual.d90 = sol_y[331];
  CPG_Dual.d91 = sol_y[332];
  CPG_Dual.d92 = sol_y[333];
  CPG_Dual.d93 = sol_y[334];
  CPG_Dual.d94 = sol_y[335];
  CPG_Dual.d95 = sol_y[336];
  CPG_Dual.d96 = sol_y[337];
  CPG_Dual.d97 = sol_y[338];
  CPG_Dual.d98 = sol_y[339];
  CPG_Dual.d99 = sol_y[340];
  CPG_Dual.d100 = sol_y[341];
  CPG_Dual.d101 = sol_y[342];
  CPG_Dual.d102 = sol_y[343];
  CPG_Dual.d103 = sol_y[344];
  CPG_Dual.d104 = sol_y[345];
  CPG_Dual.d105 = sol_y[346];
  CPG_Dual.d106 = sol_y[347];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (solver.info->obj_val);
  CPG_Info.iter = solver.info->iter;
  CPG_Info.status = solver.info->status;
  CPG_Info.pri_res = solver.info->prim_res;
  CPG_Info.dua_res = solver.info->dual_res;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.q) {
    cpg_canonicalize_q();
  }
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.l) {
    cpg_canonicalize_l();
  }
  if (Canon_Outdated.u) {
    cpg_canonicalize_u();
  }
  if (Canon_Outdated.q && Canon_Outdated.l && Canon_Outdated.u) {
    osqp_update_data_vec(&solver, Canon_Params.q, Canon_Params.l, Canon_Params.u);
  } else {
    if (Canon_Outdated.q && Canon_Outdated.l) {
      osqp_update_data_vec(&solver, Canon_Params.q, Canon_Params.l, OSQP_NULL);
    } else {
      if (Canon_Outdated.q) {
        osqp_update_data_vec(&solver, Canon_Params.q, OSQP_NULL, OSQP_NULL);
      }
      if (Canon_Outdated.l) {
        osqp_update_data_vec(&solver, OSQP_NULL, Canon_Params.l, OSQP_NULL);
      }
    }
    if (Canon_Outdated.q && Canon_Outdated.u) {
      osqp_update_data_vec(&solver, Canon_Params.q, OSQP_NULL, Canon_Params.u);
    } else {
      if (Canon_Outdated.q) {
        osqp_update_data_vec(&solver, Canon_Params.q, OSQP_NULL, OSQP_NULL);
      }
      if (Canon_Outdated.u) {
        osqp_update_data_vec(&solver, OSQP_NULL, OSQP_NULL, Canon_Params.u);
      }
    }
    if (Canon_Outdated.l && Canon_Outdated.u) {
      osqp_update_data_vec(&solver, OSQP_NULL, Canon_Params.l, Canon_Params.u);
    } else {
      if (Canon_Outdated.l) {
        osqp_update_data_vec(&solver, OSQP_NULL, Canon_Params.l, OSQP_NULL);
      }
      if (Canon_Outdated.u) {
        osqp_update_data_vec(&solver, OSQP_NULL, OSQP_NULL, Canon_Params.u);
      }
    }
  }
  if (Canon_Outdated.A) {
    osqp_update_data_mat(&solver, OSQP_NULL, 0, 0, Canon_Params.A->x, 0, Canon_Params.A->nnz);
  }
  // Solve with OSQP
  osqp_solve(&solver);
  // Retrieve results
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.q = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.l = 0;
  Canon_Outdated.u = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  osqp_set_default_settings(solver.settings);
}

void cpg_set_solver_max_iter(cpg_int max_iter_new){
  solver.settings->max_iter = max_iter_new;
}

void cpg_set_solver_eps_abs(cpg_float eps_abs_new){
  solver.settings->eps_abs = eps_abs_new;
}

void cpg_set_solver_eps_rel(cpg_float eps_rel_new){
  solver.settings->eps_rel = eps_rel_new;
}

void cpg_set_solver_eps_prim_inf(cpg_float eps_prim_inf_new){
  solver.settings->eps_prim_inf = eps_prim_inf_new;
}

void cpg_set_solver_eps_dual_inf(cpg_float eps_dual_inf_new){
  solver.settings->eps_dual_inf = eps_dual_inf_new;
}

void cpg_set_solver_scaled_termination(cpg_int scaled_termination_new){
  solver.settings->scaled_termination = scaled_termination_new;
}

void cpg_set_solver_check_termination(cpg_int check_termination_new){
  solver.settings->check_termination = check_termination_new;
}

void cpg_set_solver_warm_starting(cpg_int warm_starting_new){
  solver.settings->warm_starting = warm_starting_new;
}
