/*
 * This file was autogenerated by OSQP on Mon Jun 22 18:17:08 2026
 * 
 * This file contains the prototype for the solver structure needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#ifndef WORKSPACE_H
#define WORKSPACE_H

#include "osqp_api_types.h"

#ifdef __cplusplus
extern "C" {
#endif

  extern OSQPSolver solver;
  extern OSQPFloat sol_x[252];
  extern OSQPFloat sol_y[348];

#ifdef __cplusplus
}
#endif

#endif /* ifndef WORKSPACE_H */
