
/*
Auto-generated by CVXPYgen on June 20, 2026 at 20:26:27
Content: Python binding with pybind11
Copyright 2021-2026 Maximilian Schaller and the CVXPYgen contributors
Licensed under the Apache License, Version 2.0
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include <chrono>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.x_ref) {
        for(i=0; i<33; i++) {
            cpg_update_x_ref(i, CPG_Params_cpp.x_ref[i]);
        }
    }
    if (CPG_Updated_cpp.x0) {
        for(i=0; i<3; i++) {
            cpg_update_x0(i, CPG_Params_cpp.x0[i]);
        }
    }
    if (CPG_Updated_cpp.B_0) {
        for(i=0; i<9; i++) {
            cpg_update_B_0(i, CPG_Params_cpp.B_0[i]);
        }
    }
    if (CPG_Updated_cpp.B_1) {
        for(i=0; i<9; i++) {
            cpg_update_B_1(i, CPG_Params_cpp.B_1[i]);
        }
    }
    if (CPG_Updated_cpp.B_2) {
        for(i=0; i<9; i++) {
            cpg_update_B_2(i, CPG_Params_cpp.B_2[i]);
        }
    }
    if (CPG_Updated_cpp.B_3) {
        for(i=0; i<9; i++) {
            cpg_update_B_3(i, CPG_Params_cpp.B_3[i]);
        }
    }
    if (CPG_Updated_cpp.B_4) {
        for(i=0; i<9; i++) {
            cpg_update_B_4(i, CPG_Params_cpp.B_4[i]);
        }
    }
    if (CPG_Updated_cpp.B_5) {
        for(i=0; i<9; i++) {
            cpg_update_B_5(i, CPG_Params_cpp.B_5[i]);
        }
    }
    if (CPG_Updated_cpp.B_6) {
        for(i=0; i<9; i++) {
            cpg_update_B_6(i, CPG_Params_cpp.B_6[i]);
        }
    }
    if (CPG_Updated_cpp.B_7) {
        for(i=0; i<9; i++) {
            cpg_update_B_7(i, CPG_Params_cpp.B_7[i]);
        }
    }
    if (CPG_Updated_cpp.B_8) {
        for(i=0; i<9; i++) {
            cpg_update_B_8(i, CPG_Params_cpp.B_8[i]);
        }
    }
    if (CPG_Updated_cpp.B_9) {
        for(i=0; i<9; i++) {
            cpg_update_B_9(i, CPG_Params_cpp.B_9[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_0) {
        cpg_update_d_0_0(CPG_Params_cpp.d_0_0);
    }
    if (CPG_Updated_cpp.n_0_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_0(i, CPG_Params_cpp.n_0_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_1) {
        cpg_update_d_0_1(CPG_Params_cpp.d_0_1);
    }
    if (CPG_Updated_cpp.n_0_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_1(i, CPG_Params_cpp.n_0_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_2) {
        cpg_update_d_0_2(CPG_Params_cpp.d_0_2);
    }
    if (CPG_Updated_cpp.n_0_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_2(i, CPG_Params_cpp.n_0_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_3) {
        cpg_update_d_0_3(CPG_Params_cpp.d_0_3);
    }
    if (CPG_Updated_cpp.n_0_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_3(i, CPG_Params_cpp.n_0_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_4) {
        cpg_update_d_0_4(CPG_Params_cpp.d_0_4);
    }
    if (CPG_Updated_cpp.n_0_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_4(i, CPG_Params_cpp.n_0_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_0_5) {
        cpg_update_d_0_5(CPG_Params_cpp.d_0_5);
    }
    if (CPG_Updated_cpp.n_0_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_0_5(i, CPG_Params_cpp.n_0_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_0) {
        cpg_update_d_1_0(CPG_Params_cpp.d_1_0);
    }
    if (CPG_Updated_cpp.n_1_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_0(i, CPG_Params_cpp.n_1_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_1) {
        cpg_update_d_1_1(CPG_Params_cpp.d_1_1);
    }
    if (CPG_Updated_cpp.n_1_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_1(i, CPG_Params_cpp.n_1_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_2) {
        cpg_update_d_1_2(CPG_Params_cpp.d_1_2);
    }
    if (CPG_Updated_cpp.n_1_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_2(i, CPG_Params_cpp.n_1_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_3) {
        cpg_update_d_1_3(CPG_Params_cpp.d_1_3);
    }
    if (CPG_Updated_cpp.n_1_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_3(i, CPG_Params_cpp.n_1_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_4) {
        cpg_update_d_1_4(CPG_Params_cpp.d_1_4);
    }
    if (CPG_Updated_cpp.n_1_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_4(i, CPG_Params_cpp.n_1_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_1_5) {
        cpg_update_d_1_5(CPG_Params_cpp.d_1_5);
    }
    if (CPG_Updated_cpp.n_1_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_1_5(i, CPG_Params_cpp.n_1_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_0) {
        cpg_update_d_2_0(CPG_Params_cpp.d_2_0);
    }
    if (CPG_Updated_cpp.n_2_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_0(i, CPG_Params_cpp.n_2_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_1) {
        cpg_update_d_2_1(CPG_Params_cpp.d_2_1);
    }
    if (CPG_Updated_cpp.n_2_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_1(i, CPG_Params_cpp.n_2_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_2) {
        cpg_update_d_2_2(CPG_Params_cpp.d_2_2);
    }
    if (CPG_Updated_cpp.n_2_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_2(i, CPG_Params_cpp.n_2_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_3) {
        cpg_update_d_2_3(CPG_Params_cpp.d_2_3);
    }
    if (CPG_Updated_cpp.n_2_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_3(i, CPG_Params_cpp.n_2_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_4) {
        cpg_update_d_2_4(CPG_Params_cpp.d_2_4);
    }
    if (CPG_Updated_cpp.n_2_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_4(i, CPG_Params_cpp.n_2_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_2_5) {
        cpg_update_d_2_5(CPG_Params_cpp.d_2_5);
    }
    if (CPG_Updated_cpp.n_2_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_2_5(i, CPG_Params_cpp.n_2_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_0) {
        cpg_update_d_3_0(CPG_Params_cpp.d_3_0);
    }
    if (CPG_Updated_cpp.n_3_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_0(i, CPG_Params_cpp.n_3_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_1) {
        cpg_update_d_3_1(CPG_Params_cpp.d_3_1);
    }
    if (CPG_Updated_cpp.n_3_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_1(i, CPG_Params_cpp.n_3_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_2) {
        cpg_update_d_3_2(CPG_Params_cpp.d_3_2);
    }
    if (CPG_Updated_cpp.n_3_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_2(i, CPG_Params_cpp.n_3_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_3) {
        cpg_update_d_3_3(CPG_Params_cpp.d_3_3);
    }
    if (CPG_Updated_cpp.n_3_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_3(i, CPG_Params_cpp.n_3_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_4) {
        cpg_update_d_3_4(CPG_Params_cpp.d_3_4);
    }
    if (CPG_Updated_cpp.n_3_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_4(i, CPG_Params_cpp.n_3_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_3_5) {
        cpg_update_d_3_5(CPG_Params_cpp.d_3_5);
    }
    if (CPG_Updated_cpp.n_3_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_3_5(i, CPG_Params_cpp.n_3_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_0) {
        cpg_update_d_4_0(CPG_Params_cpp.d_4_0);
    }
    if (CPG_Updated_cpp.n_4_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_0(i, CPG_Params_cpp.n_4_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_1) {
        cpg_update_d_4_1(CPG_Params_cpp.d_4_1);
    }
    if (CPG_Updated_cpp.n_4_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_1(i, CPG_Params_cpp.n_4_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_2) {
        cpg_update_d_4_2(CPG_Params_cpp.d_4_2);
    }
    if (CPG_Updated_cpp.n_4_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_2(i, CPG_Params_cpp.n_4_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_3) {
        cpg_update_d_4_3(CPG_Params_cpp.d_4_3);
    }
    if (CPG_Updated_cpp.n_4_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_3(i, CPG_Params_cpp.n_4_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_4) {
        cpg_update_d_4_4(CPG_Params_cpp.d_4_4);
    }
    if (CPG_Updated_cpp.n_4_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_4(i, CPG_Params_cpp.n_4_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_4_5) {
        cpg_update_d_4_5(CPG_Params_cpp.d_4_5);
    }
    if (CPG_Updated_cpp.n_4_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_4_5(i, CPG_Params_cpp.n_4_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_0) {
        cpg_update_d_5_0(CPG_Params_cpp.d_5_0);
    }
    if (CPG_Updated_cpp.n_5_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_0(i, CPG_Params_cpp.n_5_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_1) {
        cpg_update_d_5_1(CPG_Params_cpp.d_5_1);
    }
    if (CPG_Updated_cpp.n_5_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_1(i, CPG_Params_cpp.n_5_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_2) {
        cpg_update_d_5_2(CPG_Params_cpp.d_5_2);
    }
    if (CPG_Updated_cpp.n_5_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_2(i, CPG_Params_cpp.n_5_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_3) {
        cpg_update_d_5_3(CPG_Params_cpp.d_5_3);
    }
    if (CPG_Updated_cpp.n_5_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_3(i, CPG_Params_cpp.n_5_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_4) {
        cpg_update_d_5_4(CPG_Params_cpp.d_5_4);
    }
    if (CPG_Updated_cpp.n_5_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_4(i, CPG_Params_cpp.n_5_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_5_5) {
        cpg_update_d_5_5(CPG_Params_cpp.d_5_5);
    }
    if (CPG_Updated_cpp.n_5_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_5_5(i, CPG_Params_cpp.n_5_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_0) {
        cpg_update_d_6_0(CPG_Params_cpp.d_6_0);
    }
    if (CPG_Updated_cpp.n_6_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_0(i, CPG_Params_cpp.n_6_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_1) {
        cpg_update_d_6_1(CPG_Params_cpp.d_6_1);
    }
    if (CPG_Updated_cpp.n_6_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_1(i, CPG_Params_cpp.n_6_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_2) {
        cpg_update_d_6_2(CPG_Params_cpp.d_6_2);
    }
    if (CPG_Updated_cpp.n_6_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_2(i, CPG_Params_cpp.n_6_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_3) {
        cpg_update_d_6_3(CPG_Params_cpp.d_6_3);
    }
    if (CPG_Updated_cpp.n_6_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_3(i, CPG_Params_cpp.n_6_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_4) {
        cpg_update_d_6_4(CPG_Params_cpp.d_6_4);
    }
    if (CPG_Updated_cpp.n_6_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_4(i, CPG_Params_cpp.n_6_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_6_5) {
        cpg_update_d_6_5(CPG_Params_cpp.d_6_5);
    }
    if (CPG_Updated_cpp.n_6_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_6_5(i, CPG_Params_cpp.n_6_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_0) {
        cpg_update_d_7_0(CPG_Params_cpp.d_7_0);
    }
    if (CPG_Updated_cpp.n_7_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_0(i, CPG_Params_cpp.n_7_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_1) {
        cpg_update_d_7_1(CPG_Params_cpp.d_7_1);
    }
    if (CPG_Updated_cpp.n_7_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_1(i, CPG_Params_cpp.n_7_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_2) {
        cpg_update_d_7_2(CPG_Params_cpp.d_7_2);
    }
    if (CPG_Updated_cpp.n_7_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_2(i, CPG_Params_cpp.n_7_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_3) {
        cpg_update_d_7_3(CPG_Params_cpp.d_7_3);
    }
    if (CPG_Updated_cpp.n_7_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_3(i, CPG_Params_cpp.n_7_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_4) {
        cpg_update_d_7_4(CPG_Params_cpp.d_7_4);
    }
    if (CPG_Updated_cpp.n_7_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_4(i, CPG_Params_cpp.n_7_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_7_5) {
        cpg_update_d_7_5(CPG_Params_cpp.d_7_5);
    }
    if (CPG_Updated_cpp.n_7_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_7_5(i, CPG_Params_cpp.n_7_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_0) {
        cpg_update_d_8_0(CPG_Params_cpp.d_8_0);
    }
    if (CPG_Updated_cpp.n_8_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_0(i, CPG_Params_cpp.n_8_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_1) {
        cpg_update_d_8_1(CPG_Params_cpp.d_8_1);
    }
    if (CPG_Updated_cpp.n_8_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_1(i, CPG_Params_cpp.n_8_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_2) {
        cpg_update_d_8_2(CPG_Params_cpp.d_8_2);
    }
    if (CPG_Updated_cpp.n_8_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_2(i, CPG_Params_cpp.n_8_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_3) {
        cpg_update_d_8_3(CPG_Params_cpp.d_8_3);
    }
    if (CPG_Updated_cpp.n_8_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_3(i, CPG_Params_cpp.n_8_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_4) {
        cpg_update_d_8_4(CPG_Params_cpp.d_8_4);
    }
    if (CPG_Updated_cpp.n_8_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_4(i, CPG_Params_cpp.n_8_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_8_5) {
        cpg_update_d_8_5(CPG_Params_cpp.d_8_5);
    }
    if (CPG_Updated_cpp.n_8_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_8_5(i, CPG_Params_cpp.n_8_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_0) {
        cpg_update_d_9_0(CPG_Params_cpp.d_9_0);
    }
    if (CPG_Updated_cpp.n_9_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_0(i, CPG_Params_cpp.n_9_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_1) {
        cpg_update_d_9_1(CPG_Params_cpp.d_9_1);
    }
    if (CPG_Updated_cpp.n_9_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_1(i, CPG_Params_cpp.n_9_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_2) {
        cpg_update_d_9_2(CPG_Params_cpp.d_9_2);
    }
    if (CPG_Updated_cpp.n_9_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_2(i, CPG_Params_cpp.n_9_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_3) {
        cpg_update_d_9_3(CPG_Params_cpp.d_9_3);
    }
    if (CPG_Updated_cpp.n_9_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_3(i, CPG_Params_cpp.n_9_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_4) {
        cpg_update_d_9_4(CPG_Params_cpp.d_9_4);
    }
    if (CPG_Updated_cpp.n_9_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_4(i, CPG_Params_cpp.n_9_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_9_5) {
        cpg_update_d_9_5(CPG_Params_cpp.d_9_5);
    }
    if (CPG_Updated_cpp.n_9_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_9_5(i, CPG_Params_cpp.n_9_5[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_0) {
        cpg_update_d_10_0(CPG_Params_cpp.d_10_0);
    }
    if (CPG_Updated_cpp.n_10_0) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_0(i, CPG_Params_cpp.n_10_0[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_1) {
        cpg_update_d_10_1(CPG_Params_cpp.d_10_1);
    }
    if (CPG_Updated_cpp.n_10_1) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_1(i, CPG_Params_cpp.n_10_1[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_2) {
        cpg_update_d_10_2(CPG_Params_cpp.d_10_2);
    }
    if (CPG_Updated_cpp.n_10_2) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_2(i, CPG_Params_cpp.n_10_2[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_3) {
        cpg_update_d_10_3(CPG_Params_cpp.d_10_3);
    }
    if (CPG_Updated_cpp.n_10_3) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_3(i, CPG_Params_cpp.n_10_3[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_4) {
        cpg_update_d_10_4(CPG_Params_cpp.d_10_4);
    }
    if (CPG_Updated_cpp.n_10_4) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_4(i, CPG_Params_cpp.n_10_4[i]);
        }
    }
    if (CPG_Updated_cpp.d_10_5) {
        cpg_update_d_10_5(CPG_Params_cpp.d_10_5);
    }
    if (CPG_Updated_cpp.n_10_5) {
        for(i=0; i<2; i++) {
            cpg_update_n_10_5(i, CPG_Params_cpp.n_10_5[i]);
        }
    }

    // Solve
    auto ASA_start = std::chrono::high_resolution_clock::now();
    cpg_solve();
    auto ASA_end = std::chrono::high_resolution_clock::now();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<33; i++) {
        CPG_Prim_cpp.x[i] = CPG_Prim.x[i];
    }
    for(i=0; i<30; i++) {
        CPG_Prim_cpp.u[i] = CPG_Prim.u[i];
    }
    for(i=0; i<44; i++) {
        CPG_Prim_cpp.s_wall[i] = CPG_Prim.s_wall[i];
    }
    for(i=0; i<66; i++) {
        CPG_Prim_cpp.s_obs[i] = CPG_Prim.s_obs[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    CPG_Dual_cpp.d2 = CPG_Dual.d2;
    CPG_Dual_cpp.d3 = CPG_Dual.d3;
    CPG_Dual_cpp.d4 = CPG_Dual.d4;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d5[i] = CPG_Dual.d5[i];
    }
    CPG_Dual_cpp.d6 = CPG_Dual.d6;
    CPG_Dual_cpp.d7 = CPG_Dual.d7;
    CPG_Dual_cpp.d8 = CPG_Dual.d8;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d9[i] = CPG_Dual.d9[i];
    }
    CPG_Dual_cpp.d10 = CPG_Dual.d10;
    CPG_Dual_cpp.d11 = CPG_Dual.d11;
    CPG_Dual_cpp.d12 = CPG_Dual.d12;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d13[i] = CPG_Dual.d13[i];
    }
    CPG_Dual_cpp.d14 = CPG_Dual.d14;
    CPG_Dual_cpp.d15 = CPG_Dual.d15;
    CPG_Dual_cpp.d16 = CPG_Dual.d16;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d17[i] = CPG_Dual.d17[i];
    }
    CPG_Dual_cpp.d18 = CPG_Dual.d18;
    CPG_Dual_cpp.d19 = CPG_Dual.d19;
    CPG_Dual_cpp.d20 = CPG_Dual.d20;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d21[i] = CPG_Dual.d21[i];
    }
    CPG_Dual_cpp.d22 = CPG_Dual.d22;
    CPG_Dual_cpp.d23 = CPG_Dual.d23;
    CPG_Dual_cpp.d24 = CPG_Dual.d24;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d25[i] = CPG_Dual.d25[i];
    }
    CPG_Dual_cpp.d26 = CPG_Dual.d26;
    CPG_Dual_cpp.d27 = CPG_Dual.d27;
    CPG_Dual_cpp.d28 = CPG_Dual.d28;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d29[i] = CPG_Dual.d29[i];
    }
    CPG_Dual_cpp.d30 = CPG_Dual.d30;
    CPG_Dual_cpp.d31 = CPG_Dual.d31;
    CPG_Dual_cpp.d32 = CPG_Dual.d32;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d33[i] = CPG_Dual.d33[i];
    }
    CPG_Dual_cpp.d34 = CPG_Dual.d34;
    CPG_Dual_cpp.d35 = CPG_Dual.d35;
    CPG_Dual_cpp.d36 = CPG_Dual.d36;
    for(i=0; i<3; i++) {
        CPG_Dual_cpp.d37[i] = CPG_Dual.d37[i];
    }
    CPG_Dual_cpp.d38 = CPG_Dual.d38;
    CPG_Dual_cpp.d39 = CPG_Dual.d39;
    CPG_Dual_cpp.d40 = CPG_Dual.d40;
    CPG_Dual_cpp.d41 = CPG_Dual.d41;
    CPG_Dual_cpp.d42 = CPG_Dual.d42;
    CPG_Dual_cpp.d43 = CPG_Dual.d43;
    CPG_Dual_cpp.d44 = CPG_Dual.d44;
    CPG_Dual_cpp.d45 = CPG_Dual.d45;
    CPG_Dual_cpp.d46 = CPG_Dual.d46;
    CPG_Dual_cpp.d47 = CPG_Dual.d47;
    CPG_Dual_cpp.d48 = CPG_Dual.d48;
    CPG_Dual_cpp.d49 = CPG_Dual.d49;
    CPG_Dual_cpp.d50 = CPG_Dual.d50;
    CPG_Dual_cpp.d51 = CPG_Dual.d51;
    CPG_Dual_cpp.d52 = CPG_Dual.d52;
    CPG_Dual_cpp.d53 = CPG_Dual.d53;
    CPG_Dual_cpp.d54 = CPG_Dual.d54;
    CPG_Dual_cpp.d55 = CPG_Dual.d55;
    CPG_Dual_cpp.d56 = CPG_Dual.d56;
    CPG_Dual_cpp.d57 = CPG_Dual.d57;
    CPG_Dual_cpp.d58 = CPG_Dual.d58;
    CPG_Dual_cpp.d59 = CPG_Dual.d59;
    CPG_Dual_cpp.d60 = CPG_Dual.d60;
    CPG_Dual_cpp.d61 = CPG_Dual.d61;
    CPG_Dual_cpp.d62 = CPG_Dual.d62;
    CPG_Dual_cpp.d63 = CPG_Dual.d63;
    CPG_Dual_cpp.d64 = CPG_Dual.d64;
    CPG_Dual_cpp.d65 = CPG_Dual.d65;
    CPG_Dual_cpp.d66 = CPG_Dual.d66;
    CPG_Dual_cpp.d67 = CPG_Dual.d67;
    CPG_Dual_cpp.d68 = CPG_Dual.d68;
    CPG_Dual_cpp.d69 = CPG_Dual.d69;
    CPG_Dual_cpp.d70 = CPG_Dual.d70;
    CPG_Dual_cpp.d71 = CPG_Dual.d71;
    CPG_Dual_cpp.d72 = CPG_Dual.d72;
    CPG_Dual_cpp.d73 = CPG_Dual.d73;
    CPG_Dual_cpp.d74 = CPG_Dual.d74;
    CPG_Dual_cpp.d75 = CPG_Dual.d75;
    CPG_Dual_cpp.d76 = CPG_Dual.d76;
    CPG_Dual_cpp.d77 = CPG_Dual.d77;
    CPG_Dual_cpp.d78 = CPG_Dual.d78;
    CPG_Dual_cpp.d79 = CPG_Dual.d79;
    CPG_Dual_cpp.d80 = CPG_Dual.d80;
    CPG_Dual_cpp.d81 = CPG_Dual.d81;
    CPG_Dual_cpp.d82 = CPG_Dual.d82;
    CPG_Dual_cpp.d83 = CPG_Dual.d83;
    CPG_Dual_cpp.d84 = CPG_Dual.d84;
    CPG_Dual_cpp.d85 = CPG_Dual.d85;
    CPG_Dual_cpp.d86 = CPG_Dual.d86;
    CPG_Dual_cpp.d87 = CPG_Dual.d87;
    CPG_Dual_cpp.d88 = CPG_Dual.d88;
    CPG_Dual_cpp.d89 = CPG_Dual.d89;
    CPG_Dual_cpp.d90 = CPG_Dual.d90;
    CPG_Dual_cpp.d91 = CPG_Dual.d91;
    CPG_Dual_cpp.d92 = CPG_Dual.d92;
    CPG_Dual_cpp.d93 = CPG_Dual.d93;
    CPG_Dual_cpp.d94 = CPG_Dual.d94;
    CPG_Dual_cpp.d95 = CPG_Dual.d95;
    CPG_Dual_cpp.d96 = CPG_Dual.d96;
    CPG_Dual_cpp.d97 = CPG_Dual.d97;
    CPG_Dual_cpp.d98 = CPG_Dual.d98;
    CPG_Dual_cpp.d99 = CPG_Dual.d99;
    CPG_Dual_cpp.d100 = CPG_Dual.d100;
    CPG_Dual_cpp.d101 = CPG_Dual.d101;
    CPG_Dual_cpp.d102 = CPG_Dual.d102;
    CPG_Dual_cpp.d103 = CPG_Dual.d103;
    CPG_Dual_cpp.d104 = CPG_Dual.d104;
    CPG_Dual_cpp.d105 = CPG_Dual.d105;
    CPG_Dual_cpp.d106 = CPG_Dual.d106;
    CPG_Dual_cpp.d107 = CPG_Dual.d107;
    CPG_Dual_cpp.d108 = CPG_Dual.d108;
    CPG_Dual_cpp.d109 = CPG_Dual.d109;
    CPG_Dual_cpp.d110 = CPG_Dual.d110;
    CPG_Dual_cpp.d111 = CPG_Dual.d111;
    CPG_Dual_cpp.d112 = CPG_Dual.d112;
    CPG_Dual_cpp.d113 = CPG_Dual.d113;
    CPG_Dual_cpp.d114 = CPG_Dual.d114;
    CPG_Dual_cpp.d115 = CPG_Dual.d115;
    CPG_Dual_cpp.d116 = CPG_Dual.d116;
    CPG_Dual_cpp.d117 = CPG_Dual.d117;
    CPG_Dual_cpp.d118 = CPG_Dual.d118;
    CPG_Dual_cpp.d119 = CPG_Dual.d119;
    CPG_Dual_cpp.d120 = CPG_Dual.d120;
    CPG_Dual_cpp.d121 = CPG_Dual.d121;
    CPG_Dual_cpp.d122 = CPG_Dual.d122;
    CPG_Dual_cpp.d123 = CPG_Dual.d123;
    CPG_Dual_cpp.d124 = CPG_Dual.d124;
    CPG_Dual_cpp.d125 = CPG_Dual.d125;
    CPG_Dual_cpp.d126 = CPG_Dual.d126;
    CPG_Dual_cpp.d127 = CPG_Dual.d127;
    CPG_Dual_cpp.d128 = CPG_Dual.d128;
    CPG_Dual_cpp.d129 = CPG_Dual.d129;
    CPG_Dual_cpp.d130 = CPG_Dual.d130;
    CPG_Dual_cpp.d131 = CPG_Dual.d131;
    CPG_Dual_cpp.d132 = CPG_Dual.d132;
    CPG_Dual_cpp.d133 = CPG_Dual.d133;
    CPG_Dual_cpp.d134 = CPG_Dual.d134;
    CPG_Dual_cpp.d135 = CPG_Dual.d135;
    CPG_Dual_cpp.d136 = CPG_Dual.d136;
    CPG_Dual_cpp.d137 = CPG_Dual.d137;
    CPG_Dual_cpp.d138 = CPG_Dual.d138;
    CPG_Dual_cpp.d139 = CPG_Dual.d139;
    CPG_Dual_cpp.d140 = CPG_Dual.d140;
    CPG_Dual_cpp.d141 = CPG_Dual.d141;
    CPG_Dual_cpp.d142 = CPG_Dual.d142;
    CPG_Dual_cpp.d143 = CPG_Dual.d143;
    CPG_Dual_cpp.d144 = CPG_Dual.d144;
    CPG_Dual_cpp.d145 = CPG_Dual.d145;
    CPG_Dual_cpp.d146 = CPG_Dual.d146;
    CPG_Dual_cpp.d147 = CPG_Dual.d147;
    CPG_Dual_cpp.d148 = CPG_Dual.d148;
    CPG_Dual_cpp.d149 = CPG_Dual.d149;
    CPG_Dual_cpp.d150 = CPG_Dual.d150;
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    std::chrono::duration<double> elapsed = ASA_end - ASA_start;
    CPG_Info_cpp.time = elapsed.count();
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("x_ref", &CPG_Params_cpp_t::x_ref)
            .def_readwrite("x0", &CPG_Params_cpp_t::x0)
            .def_readwrite("B_0", &CPG_Params_cpp_t::B_0)
            .def_readwrite("B_1", &CPG_Params_cpp_t::B_1)
            .def_readwrite("B_2", &CPG_Params_cpp_t::B_2)
            .def_readwrite("B_3", &CPG_Params_cpp_t::B_3)
            .def_readwrite("B_4", &CPG_Params_cpp_t::B_4)
            .def_readwrite("B_5", &CPG_Params_cpp_t::B_5)
            .def_readwrite("B_6", &CPG_Params_cpp_t::B_6)
            .def_readwrite("B_7", &CPG_Params_cpp_t::B_7)
            .def_readwrite("B_8", &CPG_Params_cpp_t::B_8)
            .def_readwrite("B_9", &CPG_Params_cpp_t::B_9)
            .def_readwrite("d_0_0", &CPG_Params_cpp_t::d_0_0)
            .def_readwrite("n_0_0", &CPG_Params_cpp_t::n_0_0)
            .def_readwrite("d_0_1", &CPG_Params_cpp_t::d_0_1)
            .def_readwrite("n_0_1", &CPG_Params_cpp_t::n_0_1)
            .def_readwrite("d_0_2", &CPG_Params_cpp_t::d_0_2)
            .def_readwrite("n_0_2", &CPG_Params_cpp_t::n_0_2)
            .def_readwrite("d_0_3", &CPG_Params_cpp_t::d_0_3)
            .def_readwrite("n_0_3", &CPG_Params_cpp_t::n_0_3)
            .def_readwrite("d_0_4", &CPG_Params_cpp_t::d_0_4)
            .def_readwrite("n_0_4", &CPG_Params_cpp_t::n_0_4)
            .def_readwrite("d_0_5", &CPG_Params_cpp_t::d_0_5)
            .def_readwrite("n_0_5", &CPG_Params_cpp_t::n_0_5)
            .def_readwrite("d_1_0", &CPG_Params_cpp_t::d_1_0)
            .def_readwrite("n_1_0", &CPG_Params_cpp_t::n_1_0)
            .def_readwrite("d_1_1", &CPG_Params_cpp_t::d_1_1)
            .def_readwrite("n_1_1", &CPG_Params_cpp_t::n_1_1)
            .def_readwrite("d_1_2", &CPG_Params_cpp_t::d_1_2)
            .def_readwrite("n_1_2", &CPG_Params_cpp_t::n_1_2)
            .def_readwrite("d_1_3", &CPG_Params_cpp_t::d_1_3)
            .def_readwrite("n_1_3", &CPG_Params_cpp_t::n_1_3)
            .def_readwrite("d_1_4", &CPG_Params_cpp_t::d_1_4)
            .def_readwrite("n_1_4", &CPG_Params_cpp_t::n_1_4)
            .def_readwrite("d_1_5", &CPG_Params_cpp_t::d_1_5)
            .def_readwrite("n_1_5", &CPG_Params_cpp_t::n_1_5)
            .def_readwrite("d_2_0", &CPG_Params_cpp_t::d_2_0)
            .def_readwrite("n_2_0", &CPG_Params_cpp_t::n_2_0)
            .def_readwrite("d_2_1", &CPG_Params_cpp_t::d_2_1)
            .def_readwrite("n_2_1", &CPG_Params_cpp_t::n_2_1)
            .def_readwrite("d_2_2", &CPG_Params_cpp_t::d_2_2)
            .def_readwrite("n_2_2", &CPG_Params_cpp_t::n_2_2)
            .def_readwrite("d_2_3", &CPG_Params_cpp_t::d_2_3)
            .def_readwrite("n_2_3", &CPG_Params_cpp_t::n_2_3)
            .def_readwrite("d_2_4", &CPG_Params_cpp_t::d_2_4)
            .def_readwrite("n_2_4", &CPG_Params_cpp_t::n_2_4)
            .def_readwrite("d_2_5", &CPG_Params_cpp_t::d_2_5)
            .def_readwrite("n_2_5", &CPG_Params_cpp_t::n_2_5)
            .def_readwrite("d_3_0", &CPG_Params_cpp_t::d_3_0)
            .def_readwrite("n_3_0", &CPG_Params_cpp_t::n_3_0)
            .def_readwrite("d_3_1", &CPG_Params_cpp_t::d_3_1)
            .def_readwrite("n_3_1", &CPG_Params_cpp_t::n_3_1)
            .def_readwrite("d_3_2", &CPG_Params_cpp_t::d_3_2)
            .def_readwrite("n_3_2", &CPG_Params_cpp_t::n_3_2)
            .def_readwrite("d_3_3", &CPG_Params_cpp_t::d_3_3)
            .def_readwrite("n_3_3", &CPG_Params_cpp_t::n_3_3)
            .def_readwrite("d_3_4", &CPG_Params_cpp_t::d_3_4)
            .def_readwrite("n_3_4", &CPG_Params_cpp_t::n_3_4)
            .def_readwrite("d_3_5", &CPG_Params_cpp_t::d_3_5)
            .def_readwrite("n_3_5", &CPG_Params_cpp_t::n_3_5)
            .def_readwrite("d_4_0", &CPG_Params_cpp_t::d_4_0)
            .def_readwrite("n_4_0", &CPG_Params_cpp_t::n_4_0)
            .def_readwrite("d_4_1", &CPG_Params_cpp_t::d_4_1)
            .def_readwrite("n_4_1", &CPG_Params_cpp_t::n_4_1)
            .def_readwrite("d_4_2", &CPG_Params_cpp_t::d_4_2)
            .def_readwrite("n_4_2", &CPG_Params_cpp_t::n_4_2)
            .def_readwrite("d_4_3", &CPG_Params_cpp_t::d_4_3)
            .def_readwrite("n_4_3", &CPG_Params_cpp_t::n_4_3)
            .def_readwrite("d_4_4", &CPG_Params_cpp_t::d_4_4)
            .def_readwrite("n_4_4", &CPG_Params_cpp_t::n_4_4)
            .def_readwrite("d_4_5", &CPG_Params_cpp_t::d_4_5)
            .def_readwrite("n_4_5", &CPG_Params_cpp_t::n_4_5)
            .def_readwrite("d_5_0", &CPG_Params_cpp_t::d_5_0)
            .def_readwrite("n_5_0", &CPG_Params_cpp_t::n_5_0)
            .def_readwrite("d_5_1", &CPG_Params_cpp_t::d_5_1)
            .def_readwrite("n_5_1", &CPG_Params_cpp_t::n_5_1)
            .def_readwrite("d_5_2", &CPG_Params_cpp_t::d_5_2)
            .def_readwrite("n_5_2", &CPG_Params_cpp_t::n_5_2)
            .def_readwrite("d_5_3", &CPG_Params_cpp_t::d_5_3)
            .def_readwrite("n_5_3", &CPG_Params_cpp_t::n_5_3)
            .def_readwrite("d_5_4", &CPG_Params_cpp_t::d_5_4)
            .def_readwrite("n_5_4", &CPG_Params_cpp_t::n_5_4)
            .def_readwrite("d_5_5", &CPG_Params_cpp_t::d_5_5)
            .def_readwrite("n_5_5", &CPG_Params_cpp_t::n_5_5)
            .def_readwrite("d_6_0", &CPG_Params_cpp_t::d_6_0)
            .def_readwrite("n_6_0", &CPG_Params_cpp_t::n_6_0)
            .def_readwrite("d_6_1", &CPG_Params_cpp_t::d_6_1)
            .def_readwrite("n_6_1", &CPG_Params_cpp_t::n_6_1)
            .def_readwrite("d_6_2", &CPG_Params_cpp_t::d_6_2)
            .def_readwrite("n_6_2", &CPG_Params_cpp_t::n_6_2)
            .def_readwrite("d_6_3", &CPG_Params_cpp_t::d_6_3)
            .def_readwrite("n_6_3", &CPG_Params_cpp_t::n_6_3)
            .def_readwrite("d_6_4", &CPG_Params_cpp_t::d_6_4)
            .def_readwrite("n_6_4", &CPG_Params_cpp_t::n_6_4)
            .def_readwrite("d_6_5", &CPG_Params_cpp_t::d_6_5)
            .def_readwrite("n_6_5", &CPG_Params_cpp_t::n_6_5)
            .def_readwrite("d_7_0", &CPG_Params_cpp_t::d_7_0)
            .def_readwrite("n_7_0", &CPG_Params_cpp_t::n_7_0)
            .def_readwrite("d_7_1", &CPG_Params_cpp_t::d_7_1)
            .def_readwrite("n_7_1", &CPG_Params_cpp_t::n_7_1)
            .def_readwrite("d_7_2", &CPG_Params_cpp_t::d_7_2)
            .def_readwrite("n_7_2", &CPG_Params_cpp_t::n_7_2)
            .def_readwrite("d_7_3", &CPG_Params_cpp_t::d_7_3)
            .def_readwrite("n_7_3", &CPG_Params_cpp_t::n_7_3)
            .def_readwrite("d_7_4", &CPG_Params_cpp_t::d_7_4)
            .def_readwrite("n_7_4", &CPG_Params_cpp_t::n_7_4)
            .def_readwrite("d_7_5", &CPG_Params_cpp_t::d_7_5)
            .def_readwrite("n_7_5", &CPG_Params_cpp_t::n_7_5)
            .def_readwrite("d_8_0", &CPG_Params_cpp_t::d_8_0)
            .def_readwrite("n_8_0", &CPG_Params_cpp_t::n_8_0)
            .def_readwrite("d_8_1", &CPG_Params_cpp_t::d_8_1)
            .def_readwrite("n_8_1", &CPG_Params_cpp_t::n_8_1)
            .def_readwrite("d_8_2", &CPG_Params_cpp_t::d_8_2)
            .def_readwrite("n_8_2", &CPG_Params_cpp_t::n_8_2)
            .def_readwrite("d_8_3", &CPG_Params_cpp_t::d_8_3)
            .def_readwrite("n_8_3", &CPG_Params_cpp_t::n_8_3)
            .def_readwrite("d_8_4", &CPG_Params_cpp_t::d_8_4)
            .def_readwrite("n_8_4", &CPG_Params_cpp_t::n_8_4)
            .def_readwrite("d_8_5", &CPG_Params_cpp_t::d_8_5)
            .def_readwrite("n_8_5", &CPG_Params_cpp_t::n_8_5)
            .def_readwrite("d_9_0", &CPG_Params_cpp_t::d_9_0)
            .def_readwrite("n_9_0", &CPG_Params_cpp_t::n_9_0)
            .def_readwrite("d_9_1", &CPG_Params_cpp_t::d_9_1)
            .def_readwrite("n_9_1", &CPG_Params_cpp_t::n_9_1)
            .def_readwrite("d_9_2", &CPG_Params_cpp_t::d_9_2)
            .def_readwrite("n_9_2", &CPG_Params_cpp_t::n_9_2)
            .def_readwrite("d_9_3", &CPG_Params_cpp_t::d_9_3)
            .def_readwrite("n_9_3", &CPG_Params_cpp_t::n_9_3)
            .def_readwrite("d_9_4", &CPG_Params_cpp_t::d_9_4)
            .def_readwrite("n_9_4", &CPG_Params_cpp_t::n_9_4)
            .def_readwrite("d_9_5", &CPG_Params_cpp_t::d_9_5)
            .def_readwrite("n_9_5", &CPG_Params_cpp_t::n_9_5)
            .def_readwrite("d_10_0", &CPG_Params_cpp_t::d_10_0)
            .def_readwrite("n_10_0", &CPG_Params_cpp_t::n_10_0)
            .def_readwrite("d_10_1", &CPG_Params_cpp_t::d_10_1)
            .def_readwrite("n_10_1", &CPG_Params_cpp_t::n_10_1)
            .def_readwrite("d_10_2", &CPG_Params_cpp_t::d_10_2)
            .def_readwrite("n_10_2", &CPG_Params_cpp_t::n_10_2)
            .def_readwrite("d_10_3", &CPG_Params_cpp_t::d_10_3)
            .def_readwrite("n_10_3", &CPG_Params_cpp_t::n_10_3)
            .def_readwrite("d_10_4", &CPG_Params_cpp_t::d_10_4)
            .def_readwrite("n_10_4", &CPG_Params_cpp_t::n_10_4)
            .def_readwrite("d_10_5", &CPG_Params_cpp_t::d_10_5)
            .def_readwrite("n_10_5", &CPG_Params_cpp_t::n_10_5)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("x_ref", &CPG_Updated_cpp_t::x_ref)
            .def_readwrite("x0", &CPG_Updated_cpp_t::x0)
            .def_readwrite("B_0", &CPG_Updated_cpp_t::B_0)
            .def_readwrite("B_1", &CPG_Updated_cpp_t::B_1)
            .def_readwrite("B_2", &CPG_Updated_cpp_t::B_2)
            .def_readwrite("B_3", &CPG_Updated_cpp_t::B_3)
            .def_readwrite("B_4", &CPG_Updated_cpp_t::B_4)
            .def_readwrite("B_5", &CPG_Updated_cpp_t::B_5)
            .def_readwrite("B_6", &CPG_Updated_cpp_t::B_6)
            .def_readwrite("B_7", &CPG_Updated_cpp_t::B_7)
            .def_readwrite("B_8", &CPG_Updated_cpp_t::B_8)
            .def_readwrite("B_9", &CPG_Updated_cpp_t::B_9)
            .def_readwrite("d_0_0", &CPG_Updated_cpp_t::d_0_0)
            .def_readwrite("n_0_0", &CPG_Updated_cpp_t::n_0_0)
            .def_readwrite("d_0_1", &CPG_Updated_cpp_t::d_0_1)
            .def_readwrite("n_0_1", &CPG_Updated_cpp_t::n_0_1)
            .def_readwrite("d_0_2", &CPG_Updated_cpp_t::d_0_2)
            .def_readwrite("n_0_2", &CPG_Updated_cpp_t::n_0_2)
            .def_readwrite("d_0_3", &CPG_Updated_cpp_t::d_0_3)
            .def_readwrite("n_0_3", &CPG_Updated_cpp_t::n_0_3)
            .def_readwrite("d_0_4", &CPG_Updated_cpp_t::d_0_4)
            .def_readwrite("n_0_4", &CPG_Updated_cpp_t::n_0_4)
            .def_readwrite("d_0_5", &CPG_Updated_cpp_t::d_0_5)
            .def_readwrite("n_0_5", &CPG_Updated_cpp_t::n_0_5)
            .def_readwrite("d_1_0", &CPG_Updated_cpp_t::d_1_0)
            .def_readwrite("n_1_0", &CPG_Updated_cpp_t::n_1_0)
            .def_readwrite("d_1_1", &CPG_Updated_cpp_t::d_1_1)
            .def_readwrite("n_1_1", &CPG_Updated_cpp_t::n_1_1)
            .def_readwrite("d_1_2", &CPG_Updated_cpp_t::d_1_2)
            .def_readwrite("n_1_2", &CPG_Updated_cpp_t::n_1_2)
            .def_readwrite("d_1_3", &CPG_Updated_cpp_t::d_1_3)
            .def_readwrite("n_1_3", &CPG_Updated_cpp_t::n_1_3)
            .def_readwrite("d_1_4", &CPG_Updated_cpp_t::d_1_4)
            .def_readwrite("n_1_4", &CPG_Updated_cpp_t::n_1_4)
            .def_readwrite("d_1_5", &CPG_Updated_cpp_t::d_1_5)
            .def_readwrite("n_1_5", &CPG_Updated_cpp_t::n_1_5)
            .def_readwrite("d_2_0", &CPG_Updated_cpp_t::d_2_0)
            .def_readwrite("n_2_0", &CPG_Updated_cpp_t::n_2_0)
            .def_readwrite("d_2_1", &CPG_Updated_cpp_t::d_2_1)
            .def_readwrite("n_2_1", &CPG_Updated_cpp_t::n_2_1)
            .def_readwrite("d_2_2", &CPG_Updated_cpp_t::d_2_2)
            .def_readwrite("n_2_2", &CPG_Updated_cpp_t::n_2_2)
            .def_readwrite("d_2_3", &CPG_Updated_cpp_t::d_2_3)
            .def_readwrite("n_2_3", &CPG_Updated_cpp_t::n_2_3)
            .def_readwrite("d_2_4", &CPG_Updated_cpp_t::d_2_4)
            .def_readwrite("n_2_4", &CPG_Updated_cpp_t::n_2_4)
            .def_readwrite("d_2_5", &CPG_Updated_cpp_t::d_2_5)
            .def_readwrite("n_2_5", &CPG_Updated_cpp_t::n_2_5)
            .def_readwrite("d_3_0", &CPG_Updated_cpp_t::d_3_0)
            .def_readwrite("n_3_0", &CPG_Updated_cpp_t::n_3_0)
            .def_readwrite("d_3_1", &CPG_Updated_cpp_t::d_3_1)
            .def_readwrite("n_3_1", &CPG_Updated_cpp_t::n_3_1)
            .def_readwrite("d_3_2", &CPG_Updated_cpp_t::d_3_2)
            .def_readwrite("n_3_2", &CPG_Updated_cpp_t::n_3_2)
            .def_readwrite("d_3_3", &CPG_Updated_cpp_t::d_3_3)
            .def_readwrite("n_3_3", &CPG_Updated_cpp_t::n_3_3)
            .def_readwrite("d_3_4", &CPG_Updated_cpp_t::d_3_4)
            .def_readwrite("n_3_4", &CPG_Updated_cpp_t::n_3_4)
            .def_readwrite("d_3_5", &CPG_Updated_cpp_t::d_3_5)
            .def_readwrite("n_3_5", &CPG_Updated_cpp_t::n_3_5)
            .def_readwrite("d_4_0", &CPG_Updated_cpp_t::d_4_0)
            .def_readwrite("n_4_0", &CPG_Updated_cpp_t::n_4_0)
            .def_readwrite("d_4_1", &CPG_Updated_cpp_t::d_4_1)
            .def_readwrite("n_4_1", &CPG_Updated_cpp_t::n_4_1)
            .def_readwrite("d_4_2", &CPG_Updated_cpp_t::d_4_2)
            .def_readwrite("n_4_2", &CPG_Updated_cpp_t::n_4_2)
            .def_readwrite("d_4_3", &CPG_Updated_cpp_t::d_4_3)
            .def_readwrite("n_4_3", &CPG_Updated_cpp_t::n_4_3)
            .def_readwrite("d_4_4", &CPG_Updated_cpp_t::d_4_4)
            .def_readwrite("n_4_4", &CPG_Updated_cpp_t::n_4_4)
            .def_readwrite("d_4_5", &CPG_Updated_cpp_t::d_4_5)
            .def_readwrite("n_4_5", &CPG_Updated_cpp_t::n_4_5)
            .def_readwrite("d_5_0", &CPG_Updated_cpp_t::d_5_0)
            .def_readwrite("n_5_0", &CPG_Updated_cpp_t::n_5_0)
            .def_readwrite("d_5_1", &CPG_Updated_cpp_t::d_5_1)
            .def_readwrite("n_5_1", &CPG_Updated_cpp_t::n_5_1)
            .def_readwrite("d_5_2", &CPG_Updated_cpp_t::d_5_2)
            .def_readwrite("n_5_2", &CPG_Updated_cpp_t::n_5_2)
            .def_readwrite("d_5_3", &CPG_Updated_cpp_t::d_5_3)
            .def_readwrite("n_5_3", &CPG_Updated_cpp_t::n_5_3)
            .def_readwrite("d_5_4", &CPG_Updated_cpp_t::d_5_4)
            .def_readwrite("n_5_4", &CPG_Updated_cpp_t::n_5_4)
            .def_readwrite("d_5_5", &CPG_Updated_cpp_t::d_5_5)
            .def_readwrite("n_5_5", &CPG_Updated_cpp_t::n_5_5)
            .def_readwrite("d_6_0", &CPG_Updated_cpp_t::d_6_0)
            .def_readwrite("n_6_0", &CPG_Updated_cpp_t::n_6_0)
            .def_readwrite("d_6_1", &CPG_Updated_cpp_t::d_6_1)
            .def_readwrite("n_6_1", &CPG_Updated_cpp_t::n_6_1)
            .def_readwrite("d_6_2", &CPG_Updated_cpp_t::d_6_2)
            .def_readwrite("n_6_2", &CPG_Updated_cpp_t::n_6_2)
            .def_readwrite("d_6_3", &CPG_Updated_cpp_t::d_6_3)
            .def_readwrite("n_6_3", &CPG_Updated_cpp_t::n_6_3)
            .def_readwrite("d_6_4", &CPG_Updated_cpp_t::d_6_4)
            .def_readwrite("n_6_4", &CPG_Updated_cpp_t::n_6_4)
            .def_readwrite("d_6_5", &CPG_Updated_cpp_t::d_6_5)
            .def_readwrite("n_6_5", &CPG_Updated_cpp_t::n_6_5)
            .def_readwrite("d_7_0", &CPG_Updated_cpp_t::d_7_0)
            .def_readwrite("n_7_0", &CPG_Updated_cpp_t::n_7_0)
            .def_readwrite("d_7_1", &CPG_Updated_cpp_t::d_7_1)
            .def_readwrite("n_7_1", &CPG_Updated_cpp_t::n_7_1)
            .def_readwrite("d_7_2", &CPG_Updated_cpp_t::d_7_2)
            .def_readwrite("n_7_2", &CPG_Updated_cpp_t::n_7_2)
            .def_readwrite("d_7_3", &CPG_Updated_cpp_t::d_7_3)
            .def_readwrite("n_7_3", &CPG_Updated_cpp_t::n_7_3)
            .def_readwrite("d_7_4", &CPG_Updated_cpp_t::d_7_4)
            .def_readwrite("n_7_4", &CPG_Updated_cpp_t::n_7_4)
            .def_readwrite("d_7_5", &CPG_Updated_cpp_t::d_7_5)
            .def_readwrite("n_7_5", &CPG_Updated_cpp_t::n_7_5)
            .def_readwrite("d_8_0", &CPG_Updated_cpp_t::d_8_0)
            .def_readwrite("n_8_0", &CPG_Updated_cpp_t::n_8_0)
            .def_readwrite("d_8_1", &CPG_Updated_cpp_t::d_8_1)
            .def_readwrite("n_8_1", &CPG_Updated_cpp_t::n_8_1)
            .def_readwrite("d_8_2", &CPG_Updated_cpp_t::d_8_2)
            .def_readwrite("n_8_2", &CPG_Updated_cpp_t::n_8_2)
            .def_readwrite("d_8_3", &CPG_Updated_cpp_t::d_8_3)
            .def_readwrite("n_8_3", &CPG_Updated_cpp_t::n_8_3)
            .def_readwrite("d_8_4", &CPG_Updated_cpp_t::d_8_4)
            .def_readwrite("n_8_4", &CPG_Updated_cpp_t::n_8_4)
            .def_readwrite("d_8_5", &CPG_Updated_cpp_t::d_8_5)
            .def_readwrite("n_8_5", &CPG_Updated_cpp_t::n_8_5)
            .def_readwrite("d_9_0", &CPG_Updated_cpp_t::d_9_0)
            .def_readwrite("n_9_0", &CPG_Updated_cpp_t::n_9_0)
            .def_readwrite("d_9_1", &CPG_Updated_cpp_t::d_9_1)
            .def_readwrite("n_9_1", &CPG_Updated_cpp_t::n_9_1)
            .def_readwrite("d_9_2", &CPG_Updated_cpp_t::d_9_2)
            .def_readwrite("n_9_2", &CPG_Updated_cpp_t::n_9_2)
            .def_readwrite("d_9_3", &CPG_Updated_cpp_t::d_9_3)
            .def_readwrite("n_9_3", &CPG_Updated_cpp_t::n_9_3)
            .def_readwrite("d_9_4", &CPG_Updated_cpp_t::d_9_4)
            .def_readwrite("n_9_4", &CPG_Updated_cpp_t::n_9_4)
            .def_readwrite("d_9_5", &CPG_Updated_cpp_t::d_9_5)
            .def_readwrite("n_9_5", &CPG_Updated_cpp_t::n_9_5)
            .def_readwrite("d_10_0", &CPG_Updated_cpp_t::d_10_0)
            .def_readwrite("n_10_0", &CPG_Updated_cpp_t::n_10_0)
            .def_readwrite("d_10_1", &CPG_Updated_cpp_t::d_10_1)
            .def_readwrite("n_10_1", &CPG_Updated_cpp_t::n_10_1)
            .def_readwrite("d_10_2", &CPG_Updated_cpp_t::d_10_2)
            .def_readwrite("n_10_2", &CPG_Updated_cpp_t::n_10_2)
            .def_readwrite("d_10_3", &CPG_Updated_cpp_t::d_10_3)
            .def_readwrite("n_10_3", &CPG_Updated_cpp_t::n_10_3)
            .def_readwrite("d_10_4", &CPG_Updated_cpp_t::d_10_4)
            .def_readwrite("n_10_4", &CPG_Updated_cpp_t::n_10_4)
            .def_readwrite("d_10_5", &CPG_Updated_cpp_t::d_10_5)
            .def_readwrite("n_10_5", &CPG_Updated_cpp_t::n_10_5)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("x", &CPG_Prim_cpp_t::x)
            .def_readwrite("u", &CPG_Prim_cpp_t::u)
            .def_readwrite("s_wall", &CPG_Prim_cpp_t::s_wall)
            .def_readwrite("s_obs", &CPG_Prim_cpp_t::s_obs)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &CPG_Dual_cpp_t::d50)
            .def_readwrite("d51", &CPG_Dual_cpp_t::d51)
            .def_readwrite("d52", &CPG_Dual_cpp_t::d52)
            .def_readwrite("d53", &CPG_Dual_cpp_t::d53)
            .def_readwrite("d54", &CPG_Dual_cpp_t::d54)
            .def_readwrite("d55", &CPG_Dual_cpp_t::d55)
            .def_readwrite("d56", &CPG_Dual_cpp_t::d56)
            .def_readwrite("d57", &CPG_Dual_cpp_t::d57)
            .def_readwrite("d58", &CPG_Dual_cpp_t::d58)
            .def_readwrite("d59", &CPG_Dual_cpp_t::d59)
            .def_readwrite("d60", &CPG_Dual_cpp_t::d60)
            .def_readwrite("d61", &CPG_Dual_cpp_t::d61)
            .def_readwrite("d62", &CPG_Dual_cpp_t::d62)
            .def_readwrite("d63", &CPG_Dual_cpp_t::d63)
            .def_readwrite("d64", &CPG_Dual_cpp_t::d64)
            .def_readwrite("d65", &CPG_Dual_cpp_t::d65)
            .def_readwrite("d66", &CPG_Dual_cpp_t::d66)
            .def_readwrite("d67", &CPG_Dual_cpp_t::d67)
            .def_readwrite("d68", &CPG_Dual_cpp_t::d68)
            .def_readwrite("d69", &CPG_Dual_cpp_t::d69)
            .def_readwrite("d70", &CPG_Dual_cpp_t::d70)
            .def_readwrite("d71", &CPG_Dual_cpp_t::d71)
            .def_readwrite("d72", &CPG_Dual_cpp_t::d72)
            .def_readwrite("d73", &CPG_Dual_cpp_t::d73)
            .def_readwrite("d74", &CPG_Dual_cpp_t::d74)
            .def_readwrite("d75", &CPG_Dual_cpp_t::d75)
            .def_readwrite("d76", &CPG_Dual_cpp_t::d76)
            .def_readwrite("d77", &CPG_Dual_cpp_t::d77)
            .def_readwrite("d78", &CPG_Dual_cpp_t::d78)
            .def_readwrite("d79", &CPG_Dual_cpp_t::d79)
            .def_readwrite("d80", &CPG_Dual_cpp_t::d80)
            .def_readwrite("d81", &CPG_Dual_cpp_t::d81)
            .def_readwrite("d82", &CPG_Dual_cpp_t::d82)
            .def_readwrite("d83", &CPG_Dual_cpp_t::d83)
            .def_readwrite("d84", &CPG_Dual_cpp_t::d84)
            .def_readwrite("d85", &CPG_Dual_cpp_t::d85)
            .def_readwrite("d86", &CPG_Dual_cpp_t::d86)
            .def_readwrite("d87", &CPG_Dual_cpp_t::d87)
            .def_readwrite("d88", &CPG_Dual_cpp_t::d88)
            .def_readwrite("d89", &CPG_Dual_cpp_t::d89)
            .def_readwrite("d90", &CPG_Dual_cpp_t::d90)
            .def_readwrite("d91", &CPG_Dual_cpp_t::d91)
            .def_readwrite("d92", &CPG_Dual_cpp_t::d92)
            .def_readwrite("d93", &CPG_Dual_cpp_t::d93)
            .def_readwrite("d94", &CPG_Dual_cpp_t::d94)
            .def_readwrite("d95", &CPG_Dual_cpp_t::d95)
            .def_readwrite("d96", &CPG_Dual_cpp_t::d96)
            .def_readwrite("d97", &CPG_Dual_cpp_t::d97)
            .def_readwrite("d98", &CPG_Dual_cpp_t::d98)
            .def_readwrite("d99", &CPG_Dual_cpp_t::d99)
            .def_readwrite("d100", &CPG_Dual_cpp_t::d100)
            .def_readwrite("d101", &CPG_Dual_cpp_t::d101)
            .def_readwrite("d102", &CPG_Dual_cpp_t::d102)
            .def_readwrite("d103", &CPG_Dual_cpp_t::d103)
            .def_readwrite("d104", &CPG_Dual_cpp_t::d104)
            .def_readwrite("d105", &CPG_Dual_cpp_t::d105)
            .def_readwrite("d106", &CPG_Dual_cpp_t::d106)
            .def_readwrite("d107", &CPG_Dual_cpp_t::d107)
            .def_readwrite("d108", &CPG_Dual_cpp_t::d108)
            .def_readwrite("d109", &CPG_Dual_cpp_t::d109)
            .def_readwrite("d110", &CPG_Dual_cpp_t::d110)
            .def_readwrite("d111", &CPG_Dual_cpp_t::d111)
            .def_readwrite("d112", &CPG_Dual_cpp_t::d112)
            .def_readwrite("d113", &CPG_Dual_cpp_t::d113)
            .def_readwrite("d114", &CPG_Dual_cpp_t::d114)
            .def_readwrite("d115", &CPG_Dual_cpp_t::d115)
            .def_readwrite("d116", &CPG_Dual_cpp_t::d116)
            .def_readwrite("d117", &CPG_Dual_cpp_t::d117)
            .def_readwrite("d118", &CPG_Dual_cpp_t::d118)
            .def_readwrite("d119", &CPG_Dual_cpp_t::d119)
            .def_readwrite("d120", &CPG_Dual_cpp_t::d120)
            .def_readwrite("d121", &CPG_Dual_cpp_t::d121)
            .def_readwrite("d122", &CPG_Dual_cpp_t::d122)
            .def_readwrite("d123", &CPG_Dual_cpp_t::d123)
            .def_readwrite("d124", &CPG_Dual_cpp_t::d124)
            .def_readwrite("d125", &CPG_Dual_cpp_t::d125)
            .def_readwrite("d126", &CPG_Dual_cpp_t::d126)
            .def_readwrite("d127", &CPG_Dual_cpp_t::d127)
            .def_readwrite("d128", &CPG_Dual_cpp_t::d128)
            .def_readwrite("d129", &CPG_Dual_cpp_t::d129)
            .def_readwrite("d130", &CPG_Dual_cpp_t::d130)
            .def_readwrite("d131", &CPG_Dual_cpp_t::d131)
            .def_readwrite("d132", &CPG_Dual_cpp_t::d132)
            .def_readwrite("d133", &CPG_Dual_cpp_t::d133)
            .def_readwrite("d134", &CPG_Dual_cpp_t::d134)
            .def_readwrite("d135", &CPG_Dual_cpp_t::d135)
            .def_readwrite("d136", &CPG_Dual_cpp_t::d136)
            .def_readwrite("d137", &CPG_Dual_cpp_t::d137)
            .def_readwrite("d138", &CPG_Dual_cpp_t::d138)
            .def_readwrite("d139", &CPG_Dual_cpp_t::d139)
            .def_readwrite("d140", &CPG_Dual_cpp_t::d140)
            .def_readwrite("d141", &CPG_Dual_cpp_t::d141)
            .def_readwrite("d142", &CPG_Dual_cpp_t::d142)
            .def_readwrite("d143", &CPG_Dual_cpp_t::d143)
            .def_readwrite("d144", &CPG_Dual_cpp_t::d144)
            .def_readwrite("d145", &CPG_Dual_cpp_t::d145)
            .def_readwrite("d146", &CPG_Dual_cpp_t::d146)
            .def_readwrite("d147", &CPG_Dual_cpp_t::d147)
            .def_readwrite("d148", &CPG_Dual_cpp_t::d148)
            .def_readwrite("d149", &CPG_Dual_cpp_t::d149)
            .def_readwrite("d150", &CPG_Dual_cpp_t::d150)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_max_iter", &cpg_set_solver_max_iter);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_prim_inf", &cpg_set_solver_eps_prim_inf);
    m.def("set_solver_eps_dual_inf", &cpg_set_solver_eps_dual_inf);
    m.def("set_solver_scaled_termination", &cpg_set_solver_scaled_termination);
    m.def("set_solver_check_termination", &cpg_set_solver_check_termination);
    m.def("set_solver_warm_starting", &cpg_set_solver_warm_starting);

}
